/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-02-18 00:30:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.work_005fkmk.iframe_005fkmk;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.or.ddit.dcum.vo.temp_StudentInfoVO;
import kr.or.ddit.dcum.vo.MemberVO;

public final class card_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.or.ddit.dcum.vo.temp_StudentInfoVO");
    _jspx_imports_classes.add("kr.or.ddit.dcum.vo.MemberVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/card.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\"></script>\r\n");
      out.write(" <script src=\"../../js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Jua&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("\tdiv {\r\n");
      out.write("\t}\r\n");
      out.write("\t\tbody{\r\n");
      out.write("\t\tfont-family: 'Jua', sans-serif;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
 
MemberVO loginMember = (MemberVO)session.getAttribute("loginUser");
temp_StudentInfoVO studentInfo = (temp_StudentInfoVO)session.getAttribute("studentInfo");
String dep_name = (String)session.getAttribute("dep_name");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/mainNotice.do\",\r\n");
      out.write("\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\tcres1 =0 ;\r\n");
      out.write("\t\t\t\tcres2=0;\r\n");
      out.write("\t\t\t\tcres3= 0;\r\n");
      out.write("\t\t\t\t$.each(res.clist, function(i,v){\r\n");
      out.write("\t\t\t\t\tcres1++;\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.each(res.tlist, function(i,v){\r\n");
      out.write("\t\t\t\t\tcres2++;\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.each(res.t2list, function(i,v){\r\n");
      out.write("\t\t\t\t\tcres3++;\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\tcode76 = \"<table border='1'  class='table table-light'> <tr><td>미수강강의</td><td><a href='../../work_psj/myclass/index.jsp' target='ifr-main'>\" + cres1 + \"개</a></td></tr>\";\r\n");
      out.write("\t\t\t\tcode76 += \"<tr><td>미제출과제</td><td><a href='../../work_psj/homework/index.jsp' target='ifr-main'>\" + cres2 + \"개</a></td></tr>\";\r\n");
      out.write("\t\t\t\tcode76 += \"<tr><td>미응시시험</td><td><a href='../../work_psj/Test/indexs.jsp' target='ifr-main'>\" + cres3 + \"개</a></td></tr>\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#d4res\").empty().append(code76);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\talert(\"상태 : \" + xhr.status)\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType : \"json\"\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("      \t\turl : \"");
      out.print(request.getContextPath());
      out.write("/classList.do\",\r\n");
      out.write("\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\tsuccess : function(res) {\r\n");
      out.write("\t\t\t\tcode = \"\";\r\n");
      out.write("\t\t\t\tcode += \"<table class='table'>\";\r\n");
      out.write("\t\t\t\t\t$.each(res, function(i, v) {\r\n");
      out.write("\t\t\t\t\t\tvar subname = v.sub_name;\r\n");
      out.write("\t\t\t\t\t\tcode += \"<tr>\";\r\n");
      out.write("\t\t\t\t\t\tcode += \"<td class='subname'> ▪ \"+ v.sub_name+ \"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\tcode += \"</table>\";\r\n");
      out.write("\t\t\t\t$(\"#pro-d4res\").html(code);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(xhr) {\r\n");
      out.write("\t\t\t\t\t\talert(\"상태 : \" + xhr.status);\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tdataType : \"json\"\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t})\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 학생 정보 -->\r\n");
 if(loginMember.getMem_sort_num().equals("1")){ 
      out.write("\r\n");
      out.write("\t<div class=\"Info\">\r\n");
      out.write("\t\t<div >\r\n");
      out.write("\t\t<img class=\"photo\" src=\"../../images/main/사자2.jpg\" align=\"left\">\r\n");
      out.write("\t\t\t<div class=\"cont\">\t\r\n");
      out.write("\t\t\t\t<span id=\"name\">");
      out.print(loginMember.getMem_name());
      out.write("님</span>\r\n");
      out.write("\t\t\t\t<span id=\"status\">[ ");
      out.print(studentInfo.getStatus());
      out.write(" ]</span>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<span id=\"type\">");
      out.print(studentInfo.getDep_name());
      out.write("</span>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/work_ysh/mail.jsp\" target=\"ifr-main\">\r\n");
      out.write("\t\t\t\t<img  class=\"icon\" src=\"../../images/icon/쪽지.png\" alt=\"쪽지\"> 쪽지함\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t\t<a type=\"button\" class=\"btn btn-primary btn-secondary\"\r\n");
      out.write("\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/work_kmk/mypage/updateInfo.jsp\" target=\"ifr-main\"'>\r\n");
      out.write("\t\t\t정보수정</a>\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-primary btn-dark\"\r\n");
      out.write("\t\t\t onclick='window.top.location.href=\"");
      out.print(request.getContextPath());
      out.write("/logout.do\"'>로그아웃</button>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"d4\">\r\n");
      out.write("<h3>\r\n");
      out.write("\t<img id=\"icon\"src=\"");
      out.print(request.getContextPath());
      out.write("/images/icon/알람시계.PNG\">\r\n");
      out.write("\t일정관리\r\n");
      out.write("</h3>\r\n");
      out.write("\t<div id=\"d4res\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 교수 정보 -->\t\r\n");
}else if(loginMember.getMem_sort_num().equals("2")){ 
      out.write("\r\n");
      out.write("\t<div class=\"Info\">\r\n");
      out.write("\t\t<div >\r\n");
      out.write("\t\t<img class=\"photo\" src=\"../../images/main/사자2.jpg\" align=\"left\">\r\n");
      out.write("\t\t\t<div class=\"cont\">\t\r\n");
      out.write("\t\t\t\t<span id=\"name\">");
      out.print(loginMember.getMem_name());
      out.write("님</span>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<span id=\"type\">");
      out.print(dep_name);
      out.write("</span>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<img class=\"icon\" src=\"../../images/icon/쪽지.png\" alt=\"쪽지\"> 쪽지함\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t\t<a type=\"button\" class=\"btn btn-primary btn-secondary\"\r\n");
      out.write("\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/work_kmk/mypage/updateInfo.jsp\" target=\"ifr-main\"'>\r\n");
      out.write("\t\t\t정보수정</a>\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-primary btn-dark\"\r\n");
      out.write("\t\t\t onclick='window.top.location.href=\"");
      out.print(request.getContextPath());
      out.write("/logout.do\"'>로그아웃</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"d4\">\r\n");
      out.write("<h3>\r\n");
      out.write("\t<img id=\"icon\"src=\"");
      out.print(request.getContextPath());
      out.write("/images/icon/목록.PNG\">\r\n");
      out.write("\t강의목록\r\n");
      out.write("</h3>\r\n");
      out.write("\t<div id=\"pro-d4res\"></div>\r\n");
      out.write("</div>\r\n");
}
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
