/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-02-17 08:04:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.work_005fpsj.qnaboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.or.ddit.dcum.vo.MemberVO;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.or.ddit.dcum.vo.MemberVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\tnumber = \"\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// select에 과목 넣어주는 이벤트\r\n");
      out.write("\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/Subjectlist.do\",\r\n");
      out.write("\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\tcode77 = \"<option class='o1'>과목을 선택하세요</option>\";\r\n");
      out.write("\t\t\t\t$.each(res, function(i, v){\r\n");
      out.write("\t\t\t\t\tcode77 += \"<option class='o1'>\" + v.sub_name + \"</option>\"\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t$(\"#s1\").html(code77)\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\talert(\"상태 : \" + xhr.status)\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType : \"json\"\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// select가 선택되었을 때 이벤트\r\n");
      out.write("\t\t$(\"#s1\").on(\"change\", function(){\r\n");
      out.write("\t\t\tdata = $(this).val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/Subjectlist2.do\",\r\n");
      out.write("\t\t\t\tdata : {\"data\" : data},\r\n");
      out.write("\t\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\tcode88 = \"<option class='o1'>과목을 선택하세요</option>\";\r\n");
      out.write("\t\t\t\t\t$.each(res, function(i,v){\r\n");
      out.write("\t\t\t\t\t\tcode88 += \"<option class='o2'>\" + v.class_name + \"</option>\"\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t$(\"#s2\").html(code88);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\t\talert(\"상태 : \" + xhr.status)\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType : \"json\"\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 질의응답 글 불러오는 이벤트\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/SelectQna.do\",\r\n");
      out.write("\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\tcode = \"\";\r\n");
      out.write("\t\t\t\tcodes = \"\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");

				MemberVO vo = (MemberVO)session.getAttribute("loginUser");
				String loginName = vo.getMem_name();
				
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.each(res, function(i,v){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tcode += \"<tr class='cont' ><td class='cc'>\" + v.board_num + \"</td>\";\r\n");
      out.write("\t\t\t\t\tcode += \"<td>\" + v.board_title + \"</td>\";\r\n");
      out.write("\t\t\t\t\tcode += \"<td>\" + v.board_writer + \"</td>\";\r\n");
      out.write("\t\t\t\t\tcode += \"<td>\" + v.board_date + \"</td><br><br><br><br>\";\r\n");
      out.write("\t\t\t\t\tcode += \"<td><input type='button' value='상세보기' data='\" + v.board_num + \"' class='btns btn btn-danger' data-toggle='modal' data-target='#myModal'></td></tr>\"\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tcodes += \"<tr class='cont' data-toggle='modal' data-target='#myModal'><td class='dd'>\" + v.board_num + \"</td>\";\r\n");
      out.write("\t\t\t\t\tcodes += \"<tr><td>제목</td><td>\" + v.board_title + \"</td></tr>\";\r\n");
      out.write("\t\t\t\t\tcodes += \"<tr><td>내용</td><td>\" + v.board_cont + \"</td></tr>\";\r\n");
      out.write("\t\t\t\t\tcodes += \"<tr><td>작성자</td><td>\" + v.board_writer + \"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\tnumber = $('.cont .cc').text();\r\n");
      out.write("\t\t\t\t$(\"#tab1\").append(code);\r\n");
      out.write("\t\t\t\t$(\"#tab2\").append(codes);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\talert(\"상태 : \" + xhr.status);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType : \"json\"\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#tab1\").on(\"click\", \".btns\", function(){\r\n");
      out.write("\t\t\tboardnum = $(this).attr(\"data\");\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/SelectQna.do\",\r\n");
      out.write("\t\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\tcodes = \"\";\r\n");
      out.write("\t\t\t\t\t$.each(res, function(i,v){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tif(v.board_num == boardnum){\r\n");
      out.write("\t\t\t\t\t\t\tcodes += \"<form><tr class='cont' data-toggle='modal' data-target='#myModal'><td class='dd bn' data='\"+v.baord_num+\"'>\" + v.board_num + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\tif(");
      out.print( "\"" +loginName +"\"" );
      out.write(" == v.board_writer){\r\n");
      out.write(" \t\t\t\t\t\t\t\tcodes += \"<td><input type='button' class='modify btn btn-danger' data='\" + v.board_num + \"' value='수정' >\"\r\n");
      out.write("\t\t\t\t\t\t\t\tcodes += \"<input type='button' class='delete btn btn-danger' data='\" + v.board_num + \"' value='삭제'></td>\" \r\n");
      out.write("/* \t\t\t\t\t\t\t\tcodebt += \"<input type='button' class='modify btn btn-danger' data='\" + v.board_num + \"' value='수정' >\"\r\n");
      out.write("\t\t\t\t\t\t\t\tcodebt += \"<input type='button' class='delete btn btn-danger' data='\" + v.board_num + \"' value='삭제'>\" */\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tcodes += \"<tr><td>제목</td><td data='\"+v.board_title+\"' class='title'>\" + v.board_title + \"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t\t\tcodes += \"<tr><td>내용</td><td data='\"+v.board_cont+\"' class='cont'>\" + v.board_cont + \"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t\t\tcodes += \"<tr><td>작성자</td><td data='\"+v.board_writer+\"' class='writer'>\" + v.board_writer + \"</td></tr></form>\";\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\tnumber = $('.cont .cc').text();\r\n");
      out.write("\t\t\t\t\t$(\"#tab2\").html(codes);\r\n");
      out.write("\t\t\t\t\t//$(\".modal-body\").append(codebt);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\t\talert(\"상태 : \" + xhr.status);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType : \"json\"\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 댓글 불러오기\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/selectRe.do\",\r\n");
      out.write("\t\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\"boardnum\" : boardnum\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\tcodet = \"<table border='1' class='table table-dark' id='tab55'>\";\r\n");
      out.write("\t\t\t\t\tcodet += \"<tr><td>작성자</td><td>내용</td><td>작성일</td></tr>\";\r\n");
      out.write("\t\t\t\t\t$.each(res, function(i, v){\r\n");
      out.write("\t\t\t\t\t\tcodet += \"<tr><td>\" + v.re_writer + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\tcodet += \"<td>\" + v.re_cont + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\tcodet += \"<td>\" + v.re_date + \"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\tcodet += \"</table>\"\r\n");
      out.write("\t\t\t\t\t$(\"#tab55\").remove();\r\n");
      out.write("\t\t\t\t\t$(\".modal-body\").append(codet);\r\n");
      out.write("\t\t\t\t\t//history.back();\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\t\talert(\"상태  : \" + xhr.status)\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType : \"json\"\r\n");
      out.write("\t\t\t}) \r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#btn\").on(\"click\", function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t/*  location.href = \"");
      out.print(request.getContextPath());
      out.write("/work_psj/qnaboard/insertqna.jsp\"; */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 상세보기 버튼 클릭시 이벤트\r\n");
      out.write(" \t\t$(\"#btn3\").on(\"click\", function(){\r\n");
      out.write(" \t\t\trecode = \"\";\r\n");
      out.write(" \t\t\trecode += \"<br><br>\";\r\n");
      out.write(" \t\t\trecode += \"<form action='");
      out.print(request.getContextPath());
      out.write("/insertRep.do' method='get'> \";\r\n");
      out.write(" \t\t\trecode += \"<textarea cols='55' rows='7' name='cont'></textarea><br><br>\";\r\n");
      out.write(" \t\t\trecode += \"<input type='text' name='bonum' hidden  id='hh' value='\" + $('.cont .dd').text() + \"'> \"\r\n");
      out.write(" \t\t\trecode += \"<input type='submit' value='답글달기' class='btn btn-danger'>\";\r\n");
      out.write(" \t\t\trecode += \"</form>\"\r\n");
      out.write(" \t\t\t\r\n");
      out.write(" \t\t\t\r\n");
      out.write(" \t\t\t$(\".modal-body\").append(recode);\r\n");
      out.write(" \t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t})  \r\n");
      out.write("\t\t\r\n");
      out.write("\t$(\"#tab2\").on(\"click\" , \".modify\", function(e){\r\n");
      out.write("// \t\te.preventDefault();\r\n");
      out.write("\t\te.stopPropagation()\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/SelectQna.do\",\r\n");
      out.write("\t\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\tmodifyForm = \"\";\r\n");
      out.write("\t\t\t\t\t$.each(res, function(i,v){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tif(v.board_num == boardnum){\r\n");
      out.write("\t\t\t\t\t\t\tmodifyForm += \"<tr class='cont' data-toggle='modal' data-target='#myModal'><td class='dd bn' data='\"+v.baord_num+\"'>\" + v.board_num + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\tif(");
      out.print( "\"" +loginName +"\"" );
      out.write(" == v.board_writer){\r\n");
      out.write("\t\t\t\t\t\t\t\tmodifyForm += \"<td><input type='submit' class='modify btn btn-danger' data='\" + v.board_num + \"' value='수정완료' ></td>\"\r\n");
      out.write("/* \t\t\t\t\t\t\t\tcodebt += \"<input type='button' class='modify btn btn-danger' data='\" + v.board_num + \"' value='수정' >\"\r\n");
      out.write("\t\t\t\t\t\t\t\tcodebt += \"<input type='button' class='delete btn btn-danger' data='\" + v.board_num + \"' value='삭제'>\" */\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tmodifyForm += \"<tr><td>제목</td> <td><input type='text' name='title' value='\"+v.board_title+\"'></td></tr>\";\r\n");
      out.write("\t\t\t\t\t\t\tmodifyForm += \"<tr><td>내용</td> <td><input type='text' name='cont' value='\"+v.board_cont+\"'></td></tr>\";\r\n");
      out.write("\t\t\t\t\t\t\tmodifyForm += \"<tr><td>작성자</td><td data='\"+v.board_writer+\"' class='writer'>\" + v.board_writer + \"</td></tr>\";\t\r\n");
      out.write("\t\t\t\t\t\t\tmodifyForm += \"<tr> <td><input type='text' hidden name='boardnum' value='\" + v.board_num + \"'></td></tr>\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\tnumber = $('.cont .cc').text();\r\n");
      out.write("\t\t\t\t\t$(\"#tab2\").html(modifyForm);\r\n");
      out.write("\t\t\t\t\t//$(\".modal-body\").append(codebt);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\t\talert(\"상태 : \" + xhr.status);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType : \"json\"\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/*location.href = \"");
      out.print(request.getContextPath());
      out.write("/work_psj/qnaboard/modify.jsp\";  */\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#tab2\").on(\"click\" , \".delete\", function(){\r\n");
      out.write("\t\t\tboardnum = $(this).attr(\"data\");\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/qnaBoardDelete.do\",\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\"boardNum\" : boardnum\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tmethod : \"get\",\r\n");
      out.write("\t\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/work_psj/qnaboard/index.jsp\";\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\t\talert(\"상태 : \" + xhr.status)\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType : \"json\"\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"d1\">\r\n");
      out.write("\t\t<h2>질의응답 게시판</h2><br>\r\n");
      out.write("\t\t<select>\r\n");
      out.write("\t\t\t<option>전체</option>\r\n");
      out.write("\t\t\t<option>제목</option>\r\n");
      out.write("\t\t\t<option>작성자</option>\r\n");
      out.write("\t\t\t<option>내용</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t<input type=\"text\" value=\"검색\">\r\n");
      out.write("\t\t<input type=\"button\" value=\"검색\" id=\"btn2\" class=\"btn btn-danger\">\r\n");
      out.write("\t\t<input type=\"button\" value=\"글등록\" id=\"btn\" class=\"btn btn-danger\" data-toggle='modal' data-target='#myModal2'><br><br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<table border='1' class='table table-light' id=\"tab1\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>글번호</td>\r\n");
      out.write("\t\t\t\t<td>제목</td>\r\n");
      out.write("\t\t\t\t<td>작성자</td>\r\n");
      out.write("\t\t\t\t<td>작성일</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("  \t\t<ul class=\"pagination\">\r\n");
      out.write("    \t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">1</a></li>\r\n");
      out.write("  \t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"modal\" id=\"myModal\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <!-- Modal Header -->\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <h4 class=\"modal-title\">질문글 상세보기</h4>\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Modal body -->\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("        \t<form action='");
      out.print(request.getContextPath());
      out.write("/qnaModify.do' method='get'>\r\n");
      out.write("        \t\t<table border='1' class='table table-light' id=\"tab2\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Modal footer -->\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-danger\"  id=\"btn3\" >답변달기</button>\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("<!-- The Modal -->\r\n");
      out.write("<div class=\"modal\" id=\"myModal2\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal Header -->\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h4 class=\"modal-title\">질문글 등록하기</h4>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <form action=\"");
      out.print(request.getContextPath());
      out.write("/insertQna.do\" method=\"get\">\r\n");
      out.write("      <!-- Modal body -->\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("      \t<h4>제목</h4>\r\n");
      out.write("\t\t<input type=\"text\" name=\"title\"><hr>\r\n");
      out.write("\t\t<h4>질문 카테고리 선택</h4>\r\n");
      out.write("\t\t<select id=\"s1\" name=\"subject\">\r\n");
      out.write("\t\t\t<option>과목을 선택하세요</option>\r\n");
      out.write("\t\t</select> <br>\r\n");
      out.write("\t\t<select id=\"s2\" name=\"class\">\r\n");
      out.write("\t\t\t<option>수업을 선택하세요</option>\r\n");
      out.write("\t\t</select> <hr>\r\n");
      out.write("\t\t<h4>내용</h4>\r\n");
      out.write("\t\t<textarea rows=\"10\" cols=\"30\" name=\"cont\"></textarea><br><br>\r\n");
      out.write("\t\t\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal footer -->\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <input type=\"submit\" class=\"btn btn-danger\" value='등록'>\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Fading modal -->\r\n");
      out.write("<div class=\"modal fade\"></div>\r\n");
      out.write("\r\n");
      out.write("<!-- Modal without animation -->\r\n");
      out.write("<div class=\"modal\"></div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
