/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-02-18 00:32:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.work_005fpsj.p_005fmanageStudent;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 학생관리 - select태그에 본인이 하고 있는 수업 리스트값 넣어주기\r\n");
      out.write("\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/pSelectSubject.do\",\r\n");
      out.write("\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\tcode = \"\";\r\n");
      out.write("\t\t\t\t$.each(res, function(i, v){\r\n");
      out.write("\t\t\t\t\tcode += \"<option>\" + v.sub_name + \"</option>\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t$(\"#s1\").append(code);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\talert(\"상태 : \" + xhr.status)\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType : \"json\"\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 첫번째 select 항목이 선택되면 실행되는 이벤트(버튼활성화, 두번재 select에 내용 넣어주기)\r\n");
      out.write("\t\t$(\"#s1\").on(\"change\", function(){\r\n");
      out.write("\t\t\tsubname = $(this).val();\r\n");
      out.write("\t\t\t$(\"#btn2\").removeAttr(\"disabled\");\r\n");
      out.write("\t\t\t$(\"#btn3\").removeAttr(\"disabled\");\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/pSelectClass.do\",\r\n");
      out.write("\t\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\"subname\" : subname\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\tcode2 = \"\";\r\n");
      out.write("\t\t\t\t\tcode3 = \"\";\r\n");
      out.write("\t\t\t\t\t$.each(res, function(i, v){\r\n");
      out.write("\t\t\t\t\t\tcode2 += \"<option>\" + v.class_name + \"</option>\"\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\tcode3 += \"<input type='text' hidden value='\" + subname + \"' class='idata'>\";\r\n");
      out.write("\t\t\t\t\t$(\"#d3\").html(code3);\r\n");
      out.write("\t\t\t\t\t$(\"#s2\").empty().append(code2);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\t\talert(\"상태  : \" + xhr.status)\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType : \"json\"\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 첫번째 select가 선택되면 해당 수업을 듣고 있는 학생들의 리스트를 출력하는 부분\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/pSelectStudent.do\",\r\n");
      out.write("\t\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\"subname\" : subname\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\tcode4 = \"\";\r\n");
      out.write("\t\t\t\t\t$.each(res, function(i, v){\r\n");
      out.write("\t\t\t\t\t\tcode4 += \"<tr><td>\" + v.mem_id + \"</td>\"\r\n");
      out.write("\t\t\t\t\t\tcode4 += \"<td>\" + v.mem_name + \"</td>\"\r\n");
      out.write("\t\t\t\t\t\tcode4 += \"<td>\" + v.mem_hp + \"</td>\"\r\n");
      out.write("\t\t\t\t\t\tcode4 += \"<td>\" + v.mem_add + \"</td></tr>\"\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t$(\"#restab\").empty().append(code4);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\t\talert(\"상태 : \" + xhr.status)\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType : \"json\"\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 두번재 select가 선택되면 출석관리 버튼 활성화\r\n");
      out.write("\t\t$(\"#s2\").on(\"change\", function(){\r\n");
      out.write("\t\t\t$(\"#btn1\").removeAttr(\"disabled\");\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 출석관리 버튼 클릭 이벤트\r\n");
      out.write("\t\t$(\"#btn1\").on(\"click\" , function(){\r\n");
      out.write("\t\t\tclassname = $(\"#s2\").val();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/ChkSelect.do\",\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\"classname\" : classname\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\tcode5 = \"<tr><td>강의명</td><td>이름</td><td>출석여부</td></tr>\";\r\n");
      out.write("\t\t\t\t\t$.each(res, function(i, v){\r\n");
      out.write("\t\t\t\t\t\tcode5 += \"<tr><td>\" + classname + \"</td><td>\" + v.mem_name + \"</td><td>\" + v.status + \"</td></tr>\"\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t$(\"#restab\").empty().append(code5);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\t\talert(\"상태  : \" + xhr.status)\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType : \"json\"\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 과제관리 선택 이벤트(제출한 과제 리스트 출력)\r\n");
      out.write("\t\t$(\"#btn2\").on(\"click\", function(){\r\n");
      out.write("\t\t\tsubname = $(\"#s1\").val();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/selectTasks.do\",\r\n");
      out.write("\t\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\"subname\" : subname\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\tcode6 = \"<tr><td>과제명</td><td>제목</td><td>내용</td><td>제출자</td><td>점수</td><td></td></tr>\";\r\n");
      out.write("\t\t\t\t\t$.each(res, function(i, v){\r\n");
      out.write("\t\t\t\t\t\tcode6 += \"<tr><td>\" + v.task_name + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\tcode6 += \"<td>\" + v.task_title + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\tcode6 += \"<td>\" + v.task_comt + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\tcode6 += \"<td>\" + v.mem_name + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\tcode6 += \"<td>\" + v.task_score + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\tcode6 += \"<td><input type='button' value='평가하기' class='btn btn-danger chkbtn' data-toggle='modal' data-target='#myModal' data='\" + v.task_num + \"'></td></tr>\"\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t$(\"#restab\").empty().append(code6);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\t\talert(\"상태 : \" + xhr.status)\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType : \"json\"\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 과제 점수 입력 이벤트\r\n");
      out.write("\t\t$(\"#restab\").on(\"click\", \".chkbtn\", function(){\r\n");
      out.write("\t\t\ttasknum = $(this).attr(\"data\");\r\n");
      out.write("\t\t\tcode7 =\"\";\r\n");
      out.write("\t\t\tcode7 += \"<table border='1' class='table table-dark'><tr><td>점수입력</td><td><input type='text' name='score'></td></tr><tr><td></td><td><input type='text' hidden value='\" + tasknum + \"' name='tasknum'></td></tr></table>\";\r\n");
      out.write("\t\t\t$(\".modal-body\").empty().append(code7);\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 성적입력을 필요 부분 성적입력 이벤트\r\n");
      out.write("\t\t$(\"#btn3\").on(\"click\", function(){\r\n");
      out.write("\t\t\tsubname = $(\"#s1\").val();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/scoreNeedStudents.do\",\r\n");
      out.write("\t\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\"subname\" : subname\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\tcode8 = \"\";\r\n");
      out.write("\t\t\t\t\tcode8 += \"<tr><td>과목명</td><td>이름</td><td>학번</td><td>점수</td><td></td></tr>\"\r\n");
      out.write("\t\t\t\t\t$.each(res, function(i, v){\r\n");
      out.write("\t\t\t\t\t\tcode8 += \"<tr><td>\" + v.sub_name + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\tcode8 += \"<td>\" + v.mem_name + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\tcode8 += \"<td>\" + v.mem_id + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\tcode8 += \"<td>\" + v.sub_score + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\tcode8 += \"<td><input type='button' value='점수 부여' class='btn btn-danger inscore' data-toggle='modal' data-target='#myModal' data='\" + v.sub_num + \"'></td></tr>\";\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t$(\"#restab\").empty().append(code8);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\t\talert(\"상태  : \" + xhr.status)\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType : \"json\"\r\n");
      out.write("\t\t\t})\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 점수입력 이벤트\r\n");
      out.write("\t\t$(\"#restab\").on(\"click\", \".inscore\" , function(){\r\n");
      out.write("\t\t\tmemid = $(this).attr(\"data\");\r\n");
      out.write("\t\t\t$(\"#ff\").attr(\"action\", \"");
      out.print(request.getContextPath());
      out.write("/insertSScore.do\");\r\n");
      out.write("\t\t\tcode9 = \"\";\r\n");
      out.write("\t\t\tcode9 += \"<table border='1' class='table table-dark'><tr><td>점수입력</td><td><input type='text' name='score'></td></tr><tr><td></td><td><input type='text' hidden value='\" + memid + \"' name='memid'></td></tr></table>\";\r\n");
      out.write("\t\t\t$(\".modal-body\").empty().append(code9)\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t})\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"d1\">\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t<select id=\"s1\">\r\n");
      out.write("\t\t\t<option>과목명을 선택해주세요</option>\r\n");
      out.write("\t\t\t<!-- 동적으로 수업 추가하기 -->\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<select id=\"s2\">\r\n");
      out.write("\t\t\t<option>강의을 선택해주세요</option>\r\n");
      out.write("\t\t\t<!-- 동적으로 강의명 추가하기 -->\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"d2\">\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t<input type=\"button\" value=\"출석관리\" id=\"btn1\" class=\"btn btn-danger\" disabled> &nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t<input type=\"button\" value=\"과제관리\" id=\"btn2\" class=\"btn btn-danger\" disabled> &nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t<input type=\"button\" value=\"성적관리\" id=\"btn3\" class=\"btn btn-danger\" disabled> &nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<h2><img src=\"");
      out.print(request.getContextPath());
      out.write("/images/icon/ff.png\">리스트</h2>\r\n");
      out.write("\t\t<table class='table table-light' id=\"restab\">\r\n");
      out.write("\t\t\t<tr id=\"restr\">\r\n");
      out.write("\t\t\t\t<td>학번</td>\r\n");
      out.write("\t\t\t\t<td>이름</td>\r\n");
      out.write("\t\t\t\t<td>핸드폰번호</td>\r\n");
      out.write("\t\t\t\t<td>주소</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"d3\">\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- The Modal -->\r\n");
      out.write("<div class=\"modal\" id=\"myModal\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal Header -->\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h4 class=\"modal-title\">Modal Heading</h4>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("\t  <form action=\"");
      out.print(request.getContextPath());
      out.write("/insertTaskScore.do\" method=\"post\" id=\"ff\">\r\n");
      out.write("      <!-- Modal body -->\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal footer -->\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <input type=\"submit\" class=\"btn btn-danger\"  value=\"제출\">\r\n");
      out.write("        <input type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\" value=\"닫기\">\r\n");
      out.write("      </div>\r\n");
      out.write("      </form>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
