/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-02-18 00:30:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.work_005fpsj.myclass;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("div{\r\n");
      out.write("\toverflow : auto;\r\n");
      out.write("\tdisplay : inline-block;\r\n");
      out.write("\tborder : 1px solid black;\r\n");
      out.write("\twidth : 98%;\r\n");
      out.write("\theight : 100px;\r\n");
      out.write("\tmargin : 1px;\r\n");
      out.write("\tpadding : 5px;\r\n");
      out.write("\tborder : 1px solid white;\r\n");
      out.write("}\r\n");
      out.write("#d1{\r\n");
      out.write("\theight : 130px;\r\n");
      out.write("}\r\n");
      out.write("#d2{\r\n");
      out.write("\theight : 350px;\r\n");
      out.write("}\r\n");
      out.write("#d3,#d4,#d5{\r\n");
      out.write("\twidth : 32.579%;\r\n");
      out.write("\theight : 500px;\r\n");
      out.write("\tfloat : left;\r\n");
      out.write("\tmargin : 1px;\r\n");
      out.write("\tpadding : 0px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t// 공지사항을 불러오는 ajax\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/Notice.do\",\r\n");
      out.write("\t\tmethod : \"post\",\r\n");
      out.write("\t\tsuccess : function(res){\r\n");
      out.write("\t\t\tcode = \"\";\r\n");
      out.write("\t\t\tcode += \"<table border='1' class='table table-light'>\";\r\n");
      out.write("\t\t\tcode += \"<tr><h2>강의공지사항</h2></tr>\";\r\n");
      out.write("\t\t\tcode += \"<tr><td>과목명</td><td>글제목</td><td>글내용</td><td>작성일</td><td>작성자</td></tr>\";\r\n");
      out.write("\t\t\t$.each(res, function(i, v){\r\n");
      out.write("\t\t\t \tcode += \"<tr><td>\" + v.sub_name + \"</td>\";\r\n");
      out.write("\t\t\t \tcode += \"<td>\" + v.board_title + \"</td>\";\r\n");
      out.write("\t\t\t \tcode += \"<td> \" + v.board_cont + \"</td>\";\r\n");
      out.write("\t\t\t \tcode += \"<td>\" + v.board_date + \"</td>\";\r\n");
      out.write("\t\t\t \tcode += \"<td>\" + v.mem_id + \"</td></tr>\";\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\tcode += \"</table>\";\r\n");
      out.write("\t\t\t$(\"#d4\").html(code);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror : function(xhr){\r\n");
      out.write("\t\t\talert(\"상태 : \" + xhr.status)\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tdataType : \"json\"\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t// 마이페이지 요약을 불러오는 ajax\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/Mypage.do\",\r\n");
      out.write("\t\tmethod : \"post\",\r\n");
      out.write("\t\tsuccess : function(res){\r\n");
      out.write("\t\t\tcode = \"<table border='1' class='table table-light'>\";\r\n");
      out.write("\t\t\tcode += \"<tr><h2>마이페이지</h2></tr>\";\r\n");
      out.write("\t\t\tcode += \"<tr><td class='mypage'>\" + res.mem_name + \" 님 반갑습니다.</td><tr>\";\r\n");
      out.write("\t\t\tcode += \"<td class='mypage'>이곳은 뭔가 적을만한거 적는곳</td><tr>\";\r\n");
      out.write("\t\t\tcode += \"<td class='mypage'>이곳은 뭔가 적을만한거 적는곳</td><tr>\";\r\n");
      out.write("\t\t\tcode += \"<td class='mypage'>이곳은 뭔가 적을만한거 적는곳</td><tr>\";\r\n");
      out.write("\t\t\tcode += \"<td class='mypage'>이곳은 뭔가 적을만한거 적는곳</td><tr>\";\r\n");
      out.write("\t\t\tcode += \"</table>\";\r\n");
      out.write("\t\t\t$(\"#d3\").html(code);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror : function(xhr){\r\n");
      out.write("\t\t\talert(\"상태 : \" + xhr.status)\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tdataType : \"json\"\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t// 강의 목록을 불러오는 ajax\r\n");
      out.write("\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/classList.do\",\r\n");
      out.write("\t\t//data : \"\",\r\n");
      out.write("\t\tmethod : \"post\",\r\n");
      out.write("\t\tsuccess : function(res){\r\n");
      out.write("\t\t\tcode = \"\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tcode += \"<h2><img id='icon'src='");
      out.print(request.getContextPath());
      out.write("/images/icon/dd.png'>내 강의 목록</h2>\";\r\n");
      out.write("\t\t\tcode += \"<table border='1' class='table table-light'>\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("// \t\t\tcode += \"<tr>내 강의 목록</tr>\";\r\n");
      out.write("\t\t\t$.each(res, function(i, v){\r\n");
      out.write("\t\t\t\tvar subname = v.sub_name;\r\n");
      out.write("\t\t\t\tcode += \"<tr><td>강의명</td>\";\r\n");
      out.write("\t\t\t\tcode += \"<td class='subname'>\" + v.sub_name + \"</td></tr>\"; \r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\tcode += \"</table>\";\r\n");
      out.write("\t\t\t$(\"#d2\").html(code);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror : function(xhr){\r\n");
      out.write("\t\t\talert(\"상태 : \" + xhr.status);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tdataType : \"json\"\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t// 강의리스트에서 강의를 눌렀을 때 이동하는 script\r\n");
      out.write("\t$(\"#d2\").on(\"click\",\".subname\", function(){\r\n");
      out.write("\t\tsubname = $(this).text();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/subnameIn.do\",\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\"subname\" : subname\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/work_psj/class/index.jsp\";\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\talert(\"상태 : \" + xhr.status);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType : \"json\"\r\n");
      out.write("\t\t})\r\n");
      out.write("\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t// 마이페이지에서 무언가를 눌렀을 때 이동하는 script\r\n");
      out.write("\t$(\"#d3\").on(\"click\", \".mypage\", function(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/work_psj/mypage/index.jsp\";\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"d2\" class=\"container \"> <h1>이곳은 멋진 백그라운드</h1></div>\r\n");
      out.write("\t<!-- <div id=\"d3\" class=\"container \"> <h1>이곳은 마이페이지 요약</h1></div>\r\n");
      out.write("\t<div id=\"d4\" class=\"container \"> <h1>이곳은 강의 리스트가 들어갈것 같다.</h1></div>\r\n");
      out.write("\t<div id=\"d5\" class=\"container \"> \r\n");
      out.write("\t\t<h2>나의일정</h2>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a>일정1</a></li>\r\n");
      out.write("\t\t\t<li><a>일정2</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
