/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-02-16 09:31:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.work_005fkmk.system;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.or.ddit.dcum.vo.Temp_ProfessorVO;
import kr.or.ddit.dcum.vo.temp_StudentInfoVO;
import java.util.List;

public final class allProfessorList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.or.ddit.dcum.vo.temp_StudentInfoVO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("kr.or.ddit.dcum.vo.Temp_ProfessorVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <title>Bootstrap Example</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/main.css\">\r\n");
      out.write("<!-- jquery -->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("h3{\r\n");
      out.write("\tdisplay: inline-block; \r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("}\r\n");
      out.write("#top-filter{\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("\tmargin-top: 15px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");

List<Temp_ProfessorVO> prolist = (List<Temp_ProfessorVO>)request.getAttribute("prolist"); 

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("cnt = 1\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$('#all-filter').on('click',function(){\r\n");
      out.write("\t\t$('#dep_num').hide()\r\n");
      out.write("\t\t$('#status').hide()\r\n");
      out.write("\t\tdep_num = $('#dn2').val();\r\n");
      out.write("\t\tconsole.log(dep_num)\r\n");
      out.write("\t})\r\n");
      out.write("\t$('#dep-filter').on('click',function(){\r\n");
      out.write("\t\t$('#status').hide()\r\n");
      out.write("\t\t$('#dep_num').show()\r\n");
      out.write("\t})\r\n");
      out.write("\t$('status-filter').on('click',function(){\r\n");
      out.write("\t\t$('#status').show()\r\n");
      out.write("\t\t$('#dep_num').hide()\r\n");
      out.write("\t\tstatus = $('#status').val();\r\n");
      out.write("\t\tconsole.log(status)\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<br>\r\n");
      out.write("<header>\r\n");
      out.write("  <h3>직원리스트</h3>\r\n");
      out.write("  \t<select id=\"top-filter\" >\r\n");
      out.write("  \t\t<option id=\"all-filter\">전체</option>\r\n");
      out.write("  \t\t<option id=\"status-filter\">재학여부</option>\r\n");
      out.write("  \t\t<option id=\"dep-filter\">학과별</option>\r\n");
      out.write("  \t</select>\r\n");
      out.write("  \t<select class='dep' name='dep_num' id='dep_num' style=\"display: none\">\r\n");
      out.write("\t\t<option value=\"10\">컴퓨터공학과</option>\r\n");
      out.write("\t\t<option value=\"20\">전자제어과</option>\r\n");
      out.write("\t\t<option value=\"30\">산업디자인학과</option>\r\n");
      out.write("\t\t<option value=\"40\">건축학과</option>\r\n");
      out.write("\t\t<option value=\"50\">경제학과</option>\r\n");
      out.write("\t\t<option value=\"60\">일본어과</option>\r\n");
      out.write("\t\t<option value=\"70\">영문학과</option>\r\n");
      out.write("\t\t<option value=\"80\">중국어과</option>\r\n");
      out.write("\t\t<option value=\"90\">IT 비즈니스과</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("  \t<select class='status' name='status' id='status' style=\"display: none\">\r\n");
      out.write("\t\t<option value=\"Y\">재학</option>\r\n");
      out.write("\t\t<option value=\"N\">졸업</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t<hr>\r\n");
      out.write("</header>\r\n");
      out.write("  <table class=\"table\">\r\n");
      out.write("    <thead class=\"thead-dark\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <th>순번</th>\r\n");
      out.write("        <th>이름</th>\r\n");
      out.write("        <th>학과</th>\r\n");
      out.write("        <th>아이디</th>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </thead>\r\n");
      out.write("    <tbody>\r\n");
      out.write(" ");
for(int i = 0 ; i < prolist.size() ; i++){
      out.write("\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td><script type=\"text/javascript\">document.write(cnt++)</script></td>\r\n");
      out.write("        <td>");
      out.print(prolist.get(i).getMem_name());
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print(prolist.get(i).getDep_name());
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print(prolist.get(i).getMem_id());
      out.write("</td>\r\n");
      out.write("      </tr>\r\n");
      out.write(" ");
}
      out.write("\r\n");
      out.write("    </tbody>\r\n");
      out.write("  </table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
