/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-02-16 11:54:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.work_005fkmk.system;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class InsertMember_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<!-- Core theme CSS (includes Bootstrap) -->\r\n");
      out.write("<link href=\"css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#add1\").on(\"click\", function(){\r\n");
      out.write("\t\t    new daum.Postcode({\r\n");
      out.write("\t\t        oncomplete: function(data) {\r\n");
      out.write("\t\t        \ttt = data.jibunAddress\r\n");
      out.write("\t\t            $(\"#add\").val(tt);\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t    }).open();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#cs\").on(\"click\", function() {\r\n");
      out.write("\t\t\t$(\"#sortnum\").val(\"1\").attr(\"readonly\", true);\r\n");
      out.write("\t\t\t$(\"#sortnm\").val(\"학생\").attr(\"readonly\", true);\r\n");
      out.write("\t\t\t$(\"#student\").show();\r\n");
      out.write("\t\t\t$(\"#id\").val(\"\");\r\n");
      out.write("\t\t\t$(\"#professor\").val(\"\").hide();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#dn1\").on(\"change\", function(){\r\n");
      out.write("\t\t\t\tnum1 = $(\"#sd\").val().substr(0,4);\r\n");
      out.write("\t\t\t\tnum2 = $(\".dn\").val();\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/joinSelectS.do\",\r\n");
      out.write("\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\"num1\" : num1,\r\n");
      out.write("\t\t\t\t\t\t\"num2\" : num2\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\t\t$(\"#id\").val(res.res);\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\t\t\talert(\"상태 : \" + xhr.status)\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tdataType : \"json\"\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#cp\").on(\"click\", function(){\r\n");
      out.write("\t\t\t$(\"#sortnum\").val(\"2\").attr(\"readonly\", true);\r\n");
      out.write("\t\t\t$(\"#sortnm\").val(\"교수\").attr(\"readonly\", true);\r\n");
      out.write("\t\t\t$(\"#professor\").show();\r\n");
      out.write("\t\t\t$(\"#id\").val(\"\");\r\n");
      out.write("\t\t\t$(\"#student\").val(\"\").hide();\r\n");
      out.write("\t\t\t$(\"#dn2\").on(\"change\", function(){\r\n");
      out.write("\t\t\t\tnum1 = $(\"#dn2\").val();\r\n");
      out.write("\t\t\t\tconsole.log(num1)\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/joinSelectP.do\",\r\n");
      out.write("\t\t\t\t\tdata : {\"num1\" : num1},\r\n");
      out.write("\t\t\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\t\t$(\"#id\").val(res.res);\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\t\t\talert(\"상태 : \" + xhr.status)\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tdataType : \"json\"\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("h3{\r\n");
      out.write(" display: inline-block;\r\n");
      out.write(" padding-right: 7%;\r\n");
      out.write("}\r\n");
      out.write(".type{\r\n");
      out.write("padding-right: 7%;\r\n");
      out.write("font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write(".info{\r\n");
      out.write("border-top: 1px solid;\r\n");
      out.write("border-bottom: 1px solid;\r\n");
      out.write("}\r\n");
      out.write("th{\r\n");
      out.write("width: 250px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("<br>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/join.do\" method=\"post\" id=\"join\">\r\n");
      out.write("\t\t<h3>신규 회원 등록</h3>\r\n");
      out.write("\t\t<span class=\"type\">학생<input type=\"radio\" id=\"cs\" name=\"cc\"></span>\r\n");
      out.write("\t\t<span class=\"type\">교수<input type=\"radio\" id=\"cp\" name=\"cc\"></span>\r\n");
      out.write("\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th class=\"thead-dark\">이름</th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"name\" name=\"name\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th class=\"thead-dark\">비밀번호</th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"password\" id=\"password\" name=\"password\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"1234\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th class=\"thead-dark\">생년월일</th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"bir\" name=\"bir\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th class=\"thead-dark\">성별\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t남<input type=\"checkbox\" id=\"male\" name=\"male\" value=\"남\"> \r\n");
      out.write("\t\t\t\t\t\t여<input type=\"checkbox\" id=\"female\" name=\"male\" value=\"여\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th class=\"thead-dark\">주소</th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"add\" name=\"add\">&nbsp;&nbsp;&nbsp;<input type=\"button\" id=\"add1\" name=\"add\" value=\"주소찾기\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th class=\"thead-dark\">메일</th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"mail\" name=\"mail\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th class=\"thead-dark\">전화번호</th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"hp\" name=\"hp\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"student\" class=\"info\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>입학일</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type='date' id='sd' name='sd'></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>학과번호</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<select class='dn' name='dn' id='dn1'>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"10\">컴퓨터공학과</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"20\">전자제어과</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"30\">산업디자인학과</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"40\">건축학과</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"50\">경제학과</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"60\">일본어과</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"70\">영문학과</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"80\">중국어과</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"90\">IT 비즈니스과</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"professor\" class=\"info\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>연구실 방번호</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type='text' id='prn' name='prn'></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>연구실 전화번호</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type='text' id='prh' name='prh'></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>학과번호</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<select class='dn' name='dn2' id='dn2'>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"10\" selected>컴퓨터공학과</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"20\">전자제어과</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"30\">산업디자인학과</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"40\">건축학과</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"50\">경제학과</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"60\">일본어과</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"70\">영문학과</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"80\">중국어과</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"90\">IT 비즈니스과</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"trd2\" >\r\n");
      out.write("\t\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>아이디</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" id=\"id\" name=\"id\" readonly=\"readonly\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>분류번호</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" id=\"sortnum\" name=\"sortnum\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>분류명</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" id=\"sortnm\" name=\"sortnm\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br><br>\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"가입\"> <input type=\"reset\"\r\n");
      out.write("\t\t\t\tvalue=\"취소\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
