/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-02-18 00:30:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.work_005fpsj.classComent;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 강의평가가 필요한 과목들을 불러오는 부분\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/ClassComent.do\",\r\n");
      out.write("\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\tcode = \"<table border='1' class='table table-light'><tr><td>과목명</td><td>상황</td><td></td></tr>\"\r\n");
      out.write("\t\t\t\t$.each(res, function(i, v){\r\n");
      out.write("\t\t\t\t\tcode += \"<tr><td>\" + v.sub_name + \"</td> <td>\" + v.status + \"</td>\";\r\n");
      out.write("\t\t\t\t\tcode += \"<td><input type='button' data='\" + v.sub_name + \"' class='btn btn-primary goco' data-toggle='modal' data-target='#myModal' value='등록'></td></tr>\"\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\tcode += \"</table>\"\r\n");
      out.write("\t\t\t\t$(\"#d1\").append(code);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\talert(\"상태 : \" + xhr.status)\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType : \"json\"\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 불러진 리스트 우측에 등록 버튼 이벤트\r\n");
      out.write("\t\t$(\"#d1\").on(\"click\", \".goco\", function(){\r\n");
      out.write("\t\r\n");
      out.write("\t\t\tsubname = $(this).attr(\"data\");\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/submitComent.do\",\r\n");
      out.write("\t\t\t\tmethod : \"get\",\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\"subname\" : subname\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\tcosole.log(res.gg);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\t\talert(\"상태 : \" + xhr.stauts)\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType : \"json\"\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#sub0\").on(\"click\", function(){\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/work_psj/classComent/index.jsp\";\r\n");
      out.write("\t\t\talert(\"제출되었습니다.\");\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h2>강의평가</h2>\r\n");
      out.write("\t<div id=\"d1\"></div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("  <!-- The Modal -->\r\n");
      out.write("  <div class=\"modal\" id=\"myModal\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("      \r\n");
      out.write("        <!-- Modal Header -->\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <h4 class=\"modal-title\">Modal Heading</h4>\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Modal body -->\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("         \t<form>\r\n");
      out.write("         \t\t<table border=\"1\">\r\n");
      out.write("         \t\t\t<tr>\r\n");
      out.write("         \t\t\t\t<td>제목</td>\r\n");
      out.write("         \t\t\t\t<td>체크해주세요</td>\r\n");
      out.write("         \t\t\t</tr>\r\n");
      out.write("         \t\t\t\r\n");
      out.write("         \t\t\t<tr>\r\n");
      out.write("         \t\t\t\t<td>1. 항목</td>\r\n");
      out.write("         \t\t\t\t<td>\r\n");
      out.write("         \t\t\t\t\t매우 만족<input type=\"checkbox\">\r\n");
      out.write("         \t\t\t\t\t만족<input type=\"checkbox\">\r\n");
      out.write("         \t\t\t\t\t보통<input type=\"checkbox\">\r\n");
      out.write("         \t\t\t\t\t불만족<input type=\"checkbox\">\r\n");
      out.write("         \t\t\t\t\t매우 불만족<input type=\"checkbox\">\t\r\n");
      out.write("         \t\t\t\t</td>\r\n");
      out.write("         \t\t\t</tr>\r\n");
      out.write("         \t\t\t<tr>\r\n");
      out.write("         \t\t\t\t<td>1. 항목</td>\r\n");
      out.write("         \t\t\t\t<td>\r\n");
      out.write("         \t\t\t\t\t매우 만족<input type=\"checkbox\">\r\n");
      out.write("         \t\t\t\t\t만족<input type=\"checkbox\">\r\n");
      out.write("         \t\t\t\t\t보통<input type=\"checkbox\">\r\n");
      out.write("         \t\t\t\t\t불만족<input type=\"checkbox\">\r\n");
      out.write("         \t\t\t\t\t매우 불만족<input type=\"checkbox\">\t\r\n");
      out.write("         \t\t\t\t</td>\r\n");
      out.write("         \t\t\t</tr>\r\n");
      out.write("         \t\t\t<tr>\r\n");
      out.write("         \t\t\t\t<td>1. 항목</td>\r\n");
      out.write("         \t\t\t\t<td>\r\n");
      out.write("         \t\t\t\t\t매우 만족<input type=\"checkbox\">\r\n");
      out.write("         \t\t\t\t\t만족<input type=\"checkbox\">\r\n");
      out.write("         \t\t\t\t\t보통<input type=\"checkbox\">\r\n");
      out.write("         \t\t\t\t\t불만족<input type=\"checkbox\">\r\n");
      out.write("         \t\t\t\t\t매우 불만족<input type=\"checkbox\">\t\r\n");
      out.write("         \t\t\t\t</td>\r\n");
      out.write("         \t\t\t</tr>\r\n");
      out.write("         \t\t\t<tr>\r\n");
      out.write("         \t\t\t\t<td>1. 항목</td>\r\n");
      out.write("         \t\t\t\t<td>\r\n");
      out.write("         \t\t\t\t\t매우 만족<input type=\"checkbox\">\r\n");
      out.write("         \t\t\t\t\t만족<input type=\"checkbox\">\r\n");
      out.write("         \t\t\t\t\t보통<input type=\"checkbox\">\r\n");
      out.write("         \t\t\t\t\t불만족<input type=\"checkbox\">\r\n");
      out.write("         \t\t\t\t\t매우 불만족<input type=\"checkbox\">\t\r\n");
      out.write("         \t\t\t\t</td>\r\n");
      out.write("         \t\t\t</tr>\r\n");
      out.write("         \t\t\t<tr>\r\n");
      out.write("         \t\t\t\t<td>1. 항목</td>\r\n");
      out.write("         \t\t\t\t<td>\r\n");
      out.write("         \t\t\t\t\t매우 만족<input type=\"checkbox\">\r\n");
      out.write("         \t\t\t\t\t만족<input type=\"checkbox\">\r\n");
      out.write("         \t\t\t\t\t보통<input type=\"checkbox\">\r\n");
      out.write("         \t\t\t\t\t불만족<input type=\"checkbox\">\r\n");
      out.write("         \t\t\t\t\t매우 불만족<input type=\"checkbox\">\t\r\n");
      out.write("         \t\t\t\t</td>\r\n");
      out.write("         \t\t\t</tr>\r\n");
      out.write("         \t\t</table>\r\n");
      out.write("         \t\t\t\r\n");
      out.write("         \t</form>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Modal footer -->\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\" id=\"sub0\">제출</button>\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
