/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-02-17 00:16:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.work_005fkmk.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import kr.or.ddit.dcum.vo.temp_StudentInfoVO;
import kr.or.ddit.dcum.vo.MemberVO;

public final class updateStudentStatus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.or.ddit.dcum.vo.temp_StudentInfoVO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("kr.or.ddit.dcum.vo.MemberVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<!-- Core theme CSS (includes Bootstrap) -->\r\n");
      out.write("<link href=\"css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("table th,td {\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("caption {\r\n");
      out.write("\tcaption-side: top;\r\n");
      out.write("}\r\n");
      out.write("select{\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("button {\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\tmargin: 0 100px;\r\n");
      out.write("}\r\n");
      out.write(".cause{\r\n");
      out.write("\twidth: 500px;\r\n");
      out.write("    float: left;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
 
MemberVO loginMember = (MemberVO)session.getAttribute("loginUser");
temp_StudentInfoVO studentInfo = (temp_StudentInfoVO)request.getAttribute("studentInfo");
String pro_name = (String)request.getAttribute("pro_name");

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$('#hu-but').on('click',function(){\r\n");
      out.write("\t\t$(\"#hu\").show();\r\n");
      out.write("\t\t$(\"#bok\").hide();\r\n");
      out.write("\t\t$(\"#ja\").hide();\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t$('#bok-but').on('click',function(){\r\n");
      out.write("\t\t$(\"#bok\").show();\r\n");
      out.write("\t\t$(\"#hu\").hide();\r\n");
      out.write("\t\t$(\"#ja\").hide();\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t$('#ja-but').on('click',function(){\r\n");
      out.write("\t\t$(\"#ja\").show();\r\n");
      out.write("\t\t$(\"#hu\").hide();\r\n");
      out.write("\t\t$(\"#bok\").hide();\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("})\t\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<br>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<h3>휴/복학/자퇴 신청</h3>\r\n");
      out.write("\t\t<!--   <p id=\"p1\">인적사항 외 수정사항은 관리자에게 문의하세요.</p> -->\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<caption>학과정보</caption>\r\n");
      out.write("\t\t<table class=\"table dark-table\">\r\n");
      out.write("\t\t\t<thead class=\"thead-dark\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th class=\"table-active\">이름</th>\r\n");
      out.write("\t\t\t\t\t<th class=\"table-active\">학과</th>\r\n");
      out.write("\t\t\t\t\t<th class=\"table-active\">학번</th>\r\n");
      out.write("\t\t\t\t\t<th class=\"table-active\">입학일</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(loginMember.getMem_name() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(studentInfo.getDep_name());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(studentInfo.getMem_id());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(studentInfo.getStart_date());
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\r\n");
      out.write("\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/updateStudentStatus.do\">\r\n");
      out.write("\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t<caption>[ 학적조회 ]</caption>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th class=\"table-active\">담당교수</th>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(pro_name);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<th class=\"table-active\">재학여부</th>\r\n");
      out.write("\t\t\t\t\t<td style=\"color:blue;font-weight: bold;\">\r\n");
      out.write("\t\t\t\t\t[ ");
      out.print(studentInfo.getStatus());
      out.write(" ]</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th colspan=\"2\">신청서작성</th>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t");
if(studentInfo.getStatus().equals("재학")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" id=\"hu-but\" class=\"btn btn-warning\" >휴학</button>\r\n");
      out.write("\t\t\t\t\t");
}else if(studentInfo.getStatus().equals("휴학")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" id=\"bok-but\" class=\"btn btn-success\">복학</button>\r\n");
      out.write("\t\t\t\t\t");
}else if(studentInfo.getStatus().equals("휴학신청")||
							   studentInfo.getStatus().equals("복학신청")||
							   studentInfo.getStatus().equals("자퇴신청")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" id=\"reset-but\" name=\"status\" \r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print(studentInfo.getStatus());
      out.write("\" class=\"btn btn-success\">신청취소</button>\r\n");
      out.write("\t\t\t\t\t");
}else if(studentInfo.getStatus().equals("자퇴")){
      out.write("\r\n");
      out.write("\t\t\t\t\t<span style=\"color:red;font-weight: bold;\">자퇴처리완료 _ 재입학 처리 부탁드립니다.</span>\r\n");
      out.write("\t\t\t\t\t");
}if(!studentInfo.getStatus().equals("자퇴신청")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" id=\"ja-but\" class=\"btn btn-danger\">자퇴</button>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t<div  id=\"hu\" style=\"display: none\">\r\n");
      out.write("\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/updateStudentStatus.do\">\r\n");
      out.write("\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t<caption>[ 휴학_신청정보 ]</caption>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th class=\"table-active\">휴학학기</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"hacki\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">1학기</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">2학기</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"3\">3학기</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"4\">4학기</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<th class=\"table-active\">휴학사유</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"cause\" class=\"cause\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" style=\"float: right;\" \r\n");
      out.write("\t\t\t\t\t\tname=\"status\" value=\"휴학\" class=\"btn btn-dark\">제출</button>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"bok\" style=\"display: none\">\r\n");
      out.write("\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/updateStudentStatus.do\">\r\n");
      out.write("\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t<caption>[ 복학_신청정보 ]</caption>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" style=\"float: right;\"\r\n");
      out.write("\t\t\t\t\t\tname=\"status\" value=\"복학\" class=\"btn btn-dark\">제출</button>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"ja\" style=\"display: none\">\r\n");
      out.write("\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/updateStudentStatus.do\">\r\n");
      out.write("\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t<caption>[ 자퇴_신청정보 ]</caption>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th class=\"table-active\">자퇴사유</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"cause\" class=\"cause\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" style=\"float: right;\"\r\n");
      out.write("\t\t\t\t\t\tname=\"status\" value=\"자퇴\" class=\"btn btn-dark\">제출</button>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
