/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-02-18 00:32:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.work_005fpsj.Test;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t// 진행중인 시험 리스트 불러오기\r\n");
      out.write("\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/selectTestMenu.do\",\r\n");
      out.write("\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\tcode = \"\";\r\n");
      out.write("\t\t\t\t$.each(res, function(i, v){\r\n");
      out.write("\t\t\t\t\tcode += \"<tr><td>\" + v.sub_name + \"</td>\";\r\n");
      out.write("\t\t\t\t\tcode += \"<td>\" + v.test_name + \"</td>\";\r\n");
      out.write("\t\t\t\t\tcode += \"<td><input type='button' value='상세보기' class='btn btn-danger chk' data='\" + v.sub_name + \"' data-toggle='modal' data-target='#myModal2'></td></tr>\";\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t$(\"#restab\").empty().append(code);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\talert(\"상태 : \" + xhr.status)\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType : \"json\"\r\n");
      out.write("\t\t})\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 리스트에서 상세보기 버튼 클릭 이벤트\r\n");
      out.write("\t\t$(\"#restab\").on(\"click\", \".chk\" , function(){\r\n");
      out.write("\t\t\tsubname = $(this).attr(\"data\");\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/selectTest.do\",\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\"subname\" : subname\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\tcode3 = \"\";\r\n");
      out.write("\t\t\t\t\t$.each(res, function(i, v){\r\n");
      out.write("\t\t\t\t\t\tcode3 += \"<tr><td>\" + v.sub_name + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\tcode3 += \"<td>\" + v.test_name + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\tcode3 += \"<td>\" + v.mem_name + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\tcode3 += \"<td>\" + v.score + \"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t$(\"#restab3\").empty().append(code3);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\t\talert(\"상태 : \" + xhr.status)\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType : \"json\"\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 시험등록 버튼 이벤트\r\n");
      out.write("\t\t$(\"#btn00\").on(\"click\", function(){\r\n");
      out.write("\t\t\tsubnum = $(this).attr(\"data\");\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/testSubjects.do\",\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\"subnum\" : subnum\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\tcode2 = \"\";\r\n");
      out.write("\t\t\t\t\t$.each(res, function(i, v){\r\n");
      out.write("\t\t\t\t\t\tcode2 += \"<option>\" + v.sub_name + \"</option>\"\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t$(\"#s1\").append(code2);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\t\talert(\"상태 : \" + xhr.status)\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType : \"json\"\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#s1\").on(\"change\", function(){\r\n");
      out.write("\t\t\tsubname = $(this).val();\r\n");
      out.write("\t\t\t$(\"#hin\").val(subname);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write(".t1{\r\n");
      out.write("\twidth : 350px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"d1\">\r\n");
      out.write("\t\t<h3><img src=\"/TeamProjectDCUM/images/icon/cc.png\">시험등록</h3>\r\n");
      out.write("\t\t<input type=\"button\" value=\"등록하기\" class=\"btn table-light\" data-toggle='modal' data-target='#myModal' id=\"btn00\">\r\n");
      out.write("\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/icon/aa.PNG\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"d2\">\r\n");
      out.write("\t\t<h3><img src=\"/TeamProjectDCUM/images/icon/학사관리.png\">진행중인 시험</h3>\r\n");
      out.write("\t\t<table border=\"1\" class=\"table table-light\" id=\"restab\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t  <!-- The Modal -->\r\n");
      out.write("  <div class=\"modal\" id=\"myModal\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("      \r\n");
      out.write("        <!-- Modal Header -->\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <h4 class=\"modal-title\">Modal Heading</h4>\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Modal body -->        \t\r\n");
      out.write("        <form action=\"");
      out.print(request.getContextPath());
      out.write("/insertTest.do\" method=\"post\">\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("        \t<select id=\"s1\">\r\n");
      out.write("        \t\t<option>과목을 선택해주세요.</option>\r\n");
      out.write("        \t</select><br><br>\t\r\n");
      out.write("        \t\r\n");
      out.write("        \t시험명&nbsp;&nbsp;&nbsp;<input type=\"text\" name=\"test\" class=\"t1\"><br><br>\r\n");
      out.write("        \t1번문항&nbsp;&nbsp;<input type=text name=\"q1\" class=\"t1\"><br><br>\t\r\n");
      out.write("        \t2번문항&nbsp;&nbsp;<input type=text name=\"q2\" class=\"t1\"><br><br>\t\r\n");
      out.write("        \t3번문항&nbsp;&nbsp;<input type=text name=\"q3\" class=\"t1\"><br><br>\r\n");
      out.write("        \t4번문항&nbsp;&nbsp;<input type=text name=\"q4\" class=\"t1\"><br><br>\t\r\n");
      out.write("        \t5번문항&nbsp;&nbsp;<input type=text name=\"q5\" class=\"t1\"><br><br>\t\r\n");
      out.write("        \t6번문항&nbsp;&nbsp;<input type=text name=\"q6\" class=\"t1\"><br><br>\t\r\n");
      out.write("        \t7번문항&nbsp;&nbsp;<input type=text name=\"q7\" class=\"t1\"><br><br>\t\r\n");
      out.write("        \t8번문항&nbsp;&nbsp;<input type=text name=\"q8\" class=\"t1\"><br><br>\t\r\n");
      out.write("        \t9번문항&nbsp;&nbsp;<input type=text name=\"q9\" class=\"t1\"><br><br>\t\r\n");
      out.write("        \t10번문항&nbsp;<input type=text name=\"q10\" class=\"t1\"><br><br>\r\n");
      out.write("        \t정답&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type=text name=\"answer\" class=\"t1\"><br><br>\r\n");
      out.write("        \t<input type=\"text\" hidden name=\"subname\" id=\"hin\">\r\n");
      out.write("        \t\t\r\n");
      out.write("        \t\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Modal footer -->\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("          <input type=\"submit\" class=\"btn btn-danger\" value=\"등록\">\r\n");
      out.write("         \r\n");
      out.write("          <button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        </form>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("    <div class=\"modal\" id=\"myModal2\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("      \r\n");
      out.write("        <!-- Modal Header -->\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <h4 class=\"modal-title\">Modal Heading</h4>\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Modal body -->        \t\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("\t\t\t<table class='table table-light' id=\"restab3\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Modal footer -->\r\n");
      out.write("        <div class=\"modal-footer\">         \r\n");
      out.write("          <button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
