/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-02-17 06:56:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.work_005fkjy.study;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.or.ddit.dcum.vo.MemberVO;
import kr.or.ddit.dcum.vo.StudyVO;
import java.util.List;

public final class study_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("kr.or.ddit.dcum.vo.StudyVO");
    _jspx_imports_classes.add("kr.or.ddit.dcum.vo.MemberVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>ddit cyber university</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://localhost/test/css/test.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- 게시판 -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/cmu_board.css\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");

	List<StudyVO> study = (List<StudyVO>)request.getAttribute("studyList");
	MemberVO loginMember = (MemberVO)session.getAttribute("loginUser");

      out.write("\r\n");
      out.write("\t//게시글 등록\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$('#studyForm').on('click', function(){\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/studyForm.do\";\r\n");
      out.write("\t\t})\r\n");
      out.write("\t})\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<br>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t<h2>스터디 모집</h2>\r\n");
      out.write("\t<p id=\"p1\">스터디 모집 게시판 입니다.</p> \r\n");
      out.write("\t\t<!-- 말머리 -->\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-sm \">\t\r\n");
      out.write("\t\t<form id=\"sort-form\" action=\"");
      out.print( request.getContextPath());
      out.write("/studySort.do\">\r\n");
      out.write("\t\t\t<select id=\"selectBox\" name=\"sb_sort\"  class=\"form-control mr-sm-2\">\r\n");
      out.write("\t\t\t\t<option value=\"전체\">전체</option>\r\n");
      out.write("\t\t\t\t<option value=\"모집\">모집</option>\r\n");
      out.write("\t\t\t\t<option value=\"완료\">완료</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<button type=\"submit\" id=\"sortSearch\" class=\"btn btn-info\">선택</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 검색 -->\r\n");
      out.write("\t\t<form id=\"search\" action=\"");
      out.print(request.getContextPath());
      out.write("/studySearch.do\" method=\"get\">\r\n");
      out.write("\t\t\t<input class=\"form-control mr-sm-2\" type=\"text\" placeholder=\"검색\" name=\"sb_title\">\r\n");
      out.write("\t\t\t<input class=\"btn btn-success\" type=\"submit\" value=\"검색\" id=\"titleSearch\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</nav>\t\r\n");
      out.write("\t         \r\n");
      out.write("\t\t<table class=\"table table-hover\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr class=\"table-info\">\r\n");
      out.write("\t\t\t\t\t<th id=\"no\">글번호</th>\r\n");
      out.write("\t\t\t\t\t<th id=\"sort\">말머리</th>\r\n");
      out.write("\t\t\t\t\t<th id=\"title\">제목</th>\r\n");
      out.write("\t\t\t\t\t<th id=\"wr\">글쓴이</th>\r\n");
      out.write("\t\t\t\t\t<th id=\"date\">날짜</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t");

				for(StudyVO svo : study){
			
      out.write("\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t  \t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td id=\"no\">");
      out.print( svo.getSb_num() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td id=\"sort\">[");
      out.print( svo.getSb_sort() );
      out.write("] </td>\r\n");
      out.write("\t\t\t\t\t<td id=\"title\"><a id=\"title-aTag\" href=\"");
      out.print( request.getContextPath() );
      out.write("/studyView.do?sb_num=");
      out.print( svo.getSb_num() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( svo.getSb_title() );
      out.write("</a></td>\r\n");
      out.write("\t\t\t\t\t<td id=\"wr\">");
      out.print( svo.getSb_writer() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td id=\"date\">");
      out.print( svo.getSb_date() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t\t");
 
			}
			
      out.write("\r\n");
      out.write("  \t\t</table>\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t\t<input type=\"button\" value=\"글쓰기\" id=\"studyForm\"  class=\"btn btn-secondary\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<ul class=\"pagination justify-content-center\">\r\n");
      out.write("\t\t    <li class=\"page-item\"><a class=\"page-link\" href=\"javascript:void(0);\">1</a></li>\r\n");
      out.write("\t\t    <li class=\"page-item\"><a class=\"page-link\" href=\"javascript:void(0);\">Next</a></li>\r\n");
      out.write("    \t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
