/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-02-17 04:32:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.work_005fysh;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.or.ddit.dcum.vo.MessageVO;
import kr.or.ddit.dcum.vo.MemberVO;

public final class mail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.or.ddit.dcum.vo.MemberVO");
    _jspx_imports_classes.add("kr.or.ddit.dcum.vo.MessageVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>쪽지 기능</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/student.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".container{\r\n");
      out.write("\twidth: 1000px;\r\n");
      out.write("\theight: 1000px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#la{\r\n");
      out.write("\twidth: 60px;\r\n");
      out.write("\theight: 24px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table table-striped{\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\twidth:1000px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
 

 MessageVO messge = (MessageVO)request.getAttribute("messge");
 MemberVO loginMember = (MemberVO)session.getAttribute("loginUser"); 

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//쪽지확인하기\r\n");
      out.write("\t$('#btn2').on('click',function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tmemid = '");
      out.print( loginMember.getMem_id() );
      out.write("'\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : '");
      out.print(request.getContextPath());
      out.write("/MailList.do' ,\r\n");
      out.write("\t\t\tdata : {\"memid\" : memid,\r\n");
      out.write("\t\t\t\t\"sw\" : \"1\"},\r\n");
      out.write("\t\t\ttype : 'get',\r\n");
      out.write("\t\t\tsuccess:function(res){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\tcode = \"\";\r\n");
      out.write("\t\t\t\tcode+= '<div id=\"accordion\">'\r\n");
      out.write("\t\t\t\tcode+='<h2>' + '");
      out.print(loginMember.getMem_name() );
      out.write("' + '&nbsp&nbsp님의 쪽지내역</h2>';\r\n");
      out.write("\t\t\t\tcode+='<p>'+'");
      out.print(loginMember.getMem_name() );
      out.write("'+'님 환영합니다! &nbsp&nbsp쪽지내용을 확인하세요.</p>';\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\tcode +='<table class=\"table\">'\r\n");
      out.write("\t\t\t\tcode +='    <thead class=\"thead-dark\">'\r\n");
      out.write("\t\t\t\tcode +='      <tr>'\r\n");
      out.write("\t\t\t\tcode +='        <th>번호</th>'\r\n");
      out.write("\t\t\t\tcode +='        <th>날짜</th>'\r\n");
      out.write("\t\t\t\tcode +='        <th>내용</th>'\r\n");
      out.write("\t\t\t\tcode +='        <th>보낸이</th>'\r\n");
      out.write("\t\t\t\tcode +='        <th>받는이</th>'\r\n");
      out.write("\t\t\t\tcode +='        <th></th>'\r\n");
      out.write("\t\t\t\tcode +='        <th></th>'\r\n");
      out.write("\t\t\t\tcode +='        <th></th>'\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tcode +='      </tr>'\r\n");
      out.write("\t\t\t\tcode +='    </thead>'\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.each(res,function(i, v){\r\n");
      out.write("\t\t\t\tcode +='    <tbody>'\r\n");
      out.write("\t\t\t\tcode +='      <tr>'\r\n");
      out.write("\t\t\t\tcode +='        <td>'+v.mes_num+'</td>'\r\n");
      out.write("\t\t\t\tcode +='        <td>'+v.mes_date+'</td>'\r\n");
      out.write("\t\t\t\tcode +='        <td data=\"v.mes_num\">'+v.mes_cont+'</td>'\r\n");
      out.write("\t\t\t\tcode +='        <td>'+v.bal_mem_id+'</td>'\r\n");
      out.write("\t\t\t\tcode +='        <td>'+v.su_mem_id+'</td>'\r\n");
      out.write("\t\t\t\tcode +='        <td><input type=\"button\" class=\"btn btn-primary\" id=\"inbtn\" data-toggle=\"modal\" data-target=\"#myModal\" data=\"' + v.mes_num +'\" value=\"쪽지확인\"></td>'\r\n");
      out.write("\t\t\t\tcode +='        <td><input type=\"button\" class=\"btn btn-primary delete\"  data=\"'+v.mes_num+'\" value=\"삭제하기\"></td>'\r\n");
      out.write("\t\t\t\tcode +='      </tr>'\r\n");
      out.write("\t\t\t\tcode +='      </tbody>'\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tcode +='      </table> '\r\n");
      out.write("\t\t\t\tcode +='    </div>'\r\n");
      out.write("\t\t\t\tcode += '</div>'\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#b1\").html(code);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\terror:function(xhr){\r\n");
      out.write("\t\t\t\talert(\"상태: \" + xhr.status);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType : 'json'\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\t//아작스\r\n");
      out.write("\t\r\n");
      out.write("\t})//이벤트\r\n");
      out.write("\t\r\n");
      out.write("\t//삭제이벤트 생성\r\n");
      out.write("\t$('#b1').on('click','.delete',function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tmesnum = $(this).attr(\"data\");\r\n");
      out.write("\t\talert(mesnum)\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tyn = confirm(\"정말 삭제 하시겠습니까?\");\r\n");
      out.write("\t\tif(yn){\r\n");
      out.write("\t\t\t$(this).parents('tr').remove();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/DeleteMail.do\",\r\n");
      out.write("\t\t\tdata : {\"mesnum\" : mesnum},\r\n");
      out.write("\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType : 'json'\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t})//이벤트종료\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//쪽지 불러오기\r\n");
      out.write("\t$('#b1').on('click','#inbtn',function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\tcont = $(this).attr(\"data\");\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : '");
      out.print(request.getContextPath());
      out.write("/MailList.do' ,\r\n");
      out.write("\t\t\tdata : {\"memid\" : cont,\r\n");
      out.write("\t\t\t\t\t\"sw\" : \"2\"},\r\n");
      out.write("\t\t\ttype : 'get',\t\r\n");
      out.write("\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tcodem = '';\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tcodem +='<div>'\r\n");
      out.write("\t\t\t\tcodem +='<h2>쪽지 보기</h2>'\r\n");
      out.write("\t\t\t\tcodem +='<table class=\"table table-bordered\">'\r\n");
      out.write("\t\t\t\tcodem +='<thead>'\r\n");
      out.write("\t\t\t \tcodem +='<tr>'\r\n");
      out.write("\t\t\t \tcodem +='<th>번호</th>'\r\n");
      out.write("\t\t\t\tcodem +='<th>보낸이</th>'\r\n");
      out.write("\t\t\t\tcodem +='<th>받는이</th>'\r\n");
      out.write("\t\t\t\tcodem +='<th>내용</th>'\r\n");
      out.write("\t\t\t\tcodem +='<th>날짜</th>'\r\n");
      out.write("\t\t\t\tcodem +='</tr>'\r\n");
      out.write("\t\t\t\tcodem +='</thead>'\r\n");
      out.write("\t\t\t\tcodem +='<tbody>'\r\n");
      out.write("\t\t\t\tcodem +='<tr>'\r\n");
      out.write("\t\t\t\tcodem +='<td>'+res.mes_num+'</td>'\r\n");
      out.write("\t\t\t\tcodem +='<td>'+res.bal_mem_id+'</td>'\r\n");
      out.write("\t\t\t\tcodem +='<td>'+res.su_mem_id+'</td>'\r\n");
      out.write("\t\t\t\tcodem +='<td>'+res.mes_cont+'</td>'\r\n");
      out.write("\t\t\t\tcodem +='<td>'+res.mes_date+'</td>'\t\t\t\r\n");
      out.write("\t\t\t\tcodem +='</tr>'\r\n");
      out.write("\t\t\t\tcodem +='</tbody>'\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#myModalBod\").empty().append(codem);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\talert(xhr.status);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType : 'json'\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t})//이벤트\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//쪽지 쓰기 \r\n");
      out.write("\t $('#tobtn').on('click',function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#toModal');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t })\t\r\n");
      out.write("\t \r\n");
      out.write("\t //모달창 닫기 이벤트\r\n");
      out.write("\t $('#toModal').on('hide.bs.modal', function(){\r\n");
      out.write("\t $('.text').val(\"\"); \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}) \r\n");
      out.write("\t\t\r\n");
      out.write("\t //mymailto();\r\n");
      out.write("\t //서버로 전송\t\r\n");
      out.write("\t$('#tobut').on('click',function(){\r\n");
      out.write("\t//\t console.log($('#mailin').serializeArray());\r\n");
      out.write("\t\t\r\n");
      out.write("\t\ta= confirm(\"전송하시겠습니까?\");\r\n");
      out.write("\t\tif(a){\r\n");
      out.write("\t\t    mymailto();\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$('#toModal').modal('hide');\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t/* 사용자가 듣고있는 수업들을 조회하여 s1 에 넣어주는 ajax */\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/ViewSubject.do\",\r\n");
      out.write("\t\t\tmethod : \"post\", \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tcode = \"\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.each(res, function(i, v){\r\n");
      out.write("\t\t\t\tcode += \"<option>\" + v.sub_name + \"</option>\"\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t$(\"#s1\").append(code);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\talert(\"상태 : \"+ xhr.status)\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType : \"json\"\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#s1\").on(\"change\", function(){\r\n");
      out.write("\t\tsubname = $(\"#s1\").val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/ViewSubject2.do\",\r\n");
      out.write("\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\tdata : {\"data\": subname},\r\n");
      out.write("\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\tcodee = \"\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t$.each(res, function(i, v){\r\n");
      out.write("\t\t\tcodee += \"<option>\" + v.mem_id + \"</option>\"\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t    \t$(\"#s2\").empty().append(codee);\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  //select선택하면 \r\n");
      out.write("\t\t\t  //text로\r\n");
      out.write("\t\t\t sel=$('#s2 option:selected').val();\r\n");
      out.write("\t\t\t  $('#sunam').val(sel);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\talert(\"상태 : \"+ xhr.status)\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType : \"json\"\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//2022 02 16 발신자 확인 기능\r\n");
      out.write("\t$('#btn3').on('click',function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tbalmemid = ");
      out.print(loginMember.getMem_id());
      out.write(";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/BalView.do\",\r\n");
      out.write("\t\t\tdata : {\"balmemid\" : balmemid},\r\n");
      out.write("\t\t \ttype : \"get\",\r\n");
      out.write("\t\t \tsuccess : function(res){\r\n");
      out.write("\t\t \t\t\r\n");
      out.write("\t\t\t\tcoder = '';\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tcoder +='<div>'\r\n");
      out.write("\t\t\t\tcoder +='<h2>발신 내역 확인</h2>'\r\n");
      out.write("\t\t\t\tcoder +='<table class=\"table table-striped\">'\r\n");
      out.write("\t\t\t\tcoder +='<thead>'\r\n");
      out.write("\t\t\t \tcoder +='<tr>'\r\n");
      out.write("\t\t\t \tcoder +='<th>번호</th>'\r\n");
      out.write("\t\t\t\tcoder +='<th>보낸이</th>'\r\n");
      out.write("\t\t\t\tcoder +='<th>받는이</th>'\r\n");
      out.write("\t\t\t\tcoder +='<th>내용</th>'\r\n");
      out.write("\t\t\t\tcoder +='<th>날짜</th>'\r\n");
      out.write("\t\t\t\tcoder +='</tr>'\r\n");
      out.write("\t\t\t\tcoder +='</thead>'\r\n");
      out.write("\t\t\t\tcoder +='<tbody>'\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.each(res, function(i, v){\r\n");
      out.write("\t\t\t\tcoder +='<tr>'\r\n");
      out.write("\t\t\t\tcoder +='<td>'+v.mes_num+'</td>'\r\n");
      out.write("\t\t\t\tcoder +='<td>'+v.bal_mem_id+'</td>'\r\n");
      out.write("\t\t\t\tcoder +='<td>'+v.su_mem_id+'</td>'\r\n");
      out.write("\t\t\t\tcoder +='<td>'+v.mes_cont+'</td>'\r\n");
      out.write("\t\t\t\tcoder +='<td>'+v.mes_date+'</td>'\t\r\n");
      out.write("\t\t\t\tcoder +='</tr>'\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tcoder +='</tbody>'\r\n");
      out.write("\t\t\t\tcoder +='</table>'\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#b1\").html(coder);\r\n");
      out.write("\t\t \t\t\r\n");
      out.write("\t\t \t},\r\n");
      out.write("\t\t \t\r\n");
      out.write("\t\t \t\r\n");
      out.write("\t\t \terror : function(xhr){\r\n");
      out.write("\t\t \t\t\r\n");
      out.write("\t\t \t},\r\n");
      out.write("\t\t \tdataType : 'json'\r\n");
      out.write("\t\t \t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("})// 펑션\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" <nav class=\"navbar navbar-expand-sm bg-dark navbar-dark\">\r\n");
      out.write("  <!-- Brand/logo -->\r\n");
      out.write("  <a class=\"navbar-brand\">\r\n");
      out.write("  \t<img src=\"../images/icon/쪽지.png\" alt=\"gdff\">\r\n");
      out.write("  </a>\r\n");
      out.write(" \r\n");
      out.write("   <ul class=\"navbar-nav\">\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("    \t<a class=\"nav-link\" type=\"button\" id=\"tobtn\" data-toggle=\"modal\" data-target=\"#toModal\">쪽지쓰기</a>\r\n");
      out.write("     <!-- <input class=\"nav-link\" type=\"button\" id=\"tobtn\" data-toggle=\"modal\" data-target=\"#toModal\" value=\"쪽지 쓰기\"> --> \r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("    \t<!-- <input type=\"button\" class=\"nav-link\" id=\"btn2\" value=\"쪽지 확인 하기\"> -->\r\n");
      out.write("     <a class=\"nav-link\" type=\"button\" id=\"btn2\">쪽지 확인 하기</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("   <li class=\"nav-item\">\r\n");
      out.write("    \t<!-- <input type=\"button\" class=\"nav-link\" id=\"btn2\" value=\"쪽지 확인 하기\"> -->\r\n");
      out.write("     <a class=\"nav-link\" type=\"button\" id=\"btn3\">발신 확인 하기</a>\r\n");
      out.write("    </li>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("  </ul>\r\n");
      out.write("</nav>\r\n");
      out.write("        <br><br>\r\n");
      out.write("\r\n");
      out.write("      <div id =\"b1\">\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \t<!-- 쪽지  상세확인 -->\r\n");
      out.write("\t <div class=\"modal\" id=\"myModal\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h4 class=\"modal-title\">");
      out.print(loginMember.getMem_name());
      out.write("&nbsp 님 의 쪽지</h4>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\t\t<!-- 쪽지 상세내용 조회 -->  \r\n");
      out.write("      <div class=\"modal-body\" id=\"myModalBod\">\r\n");
      out.write("      \r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div> \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 답장보내는 모달 -->\r\n");
      out.write("\t <div class=\"modal\" id=\"toModal\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h4 class=\"modal-title\">쪽지쓰기</h4>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("       \r\n");
      out.write("       <form id=\"mailin\">\r\n");
      out.write("        \t<label id=\"la\">보낸이</label>\r\n");
      out.write("        \t<input type=\"text\" id=\"banam\" name=\"banam\" value=\"");
      out.print(loginMember.getMem_id() );
      out.write("\">\r\n");
      out.write("        \t<br>\r\n");
      out.write("        \t\r\n");
      out.write("        \t<!-- ajax                 session 에서  mem_id 값 가져오고 mem_id를 가지고 이 사람이 듣고 있는 수업(subject) 를 쿼리문 보내기 -->\r\n");
      out.write("        \t<!-- ajax                 List<subjectVO> $.each <option> 태그를 만들어서 s1에 append  -->\r\n");
      out.write("        \t<!-- ajax                 $(\"#s1\").on(\"change\" function(){})  ajax  사용   sub)_name을 가지고 class_student테이블에서 학생들 조회 -->\r\n");
      out.write("        \t<!-- ajax                 List<ClassStudentVO> $.each <option> 태그를 만들어서 s2에 append -->\r\n");
      out.write("        \t\r\n");
      out.write("             <label id=\"la\">검색</label>\r\n");
      out.write("        \t<select name=\"searchtype\" id=\"s1\">\r\n");
      out.write("                <option>수업을 선택하세요.</option>\r\n");
      out.write("             </select>\r\n");
      out.write("        \t<select name=\"searchtype\" id=\"s2\">\r\n");
      out.write("                <option>상대방을 선택하세요.</option>\r\n");
      out.write("             </select>\r\n");
      out.write("        \t<br><br>\r\n");
      out.write("        \t<label id=\"la\">받는이</label>\r\n");
      out.write("        \t<input class=\"text\" type=\"text\" id=\"sunam\" name=\"sunam\" >\r\n");
      out.write("        \t<br>\r\n");
      out.write("        \t<label>내용</label>\r\n");
      out.write("        \t<br>\r\n");
      out.write("        \t<textarea class=\"text\" rows=\"10\" cols=\"50\" id=\"area\" name =\"cont\"></textarea>\r\n");
      out.write("        \r\n");
      out.write("        \t<br><br>\r\n");
      out.write("        \t<input type=\"button\" value=\"전송\" id=\"tobut\">\r\n");
      out.write("        \r\n");
      out.write("        </form>  \r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"tbtn btn-danger\" data-dismiss=\"modal\">취소</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>  \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("\t\t\tcode += '<div class=\"card\">'\r\n");
      out.write("\t\t\t\t\t\tcode += '<div class=\"card-header\">'\r\n");
      out.write("\t\t\t\tcode += '<a name=\"list\" idx=\"' + v.bal_mem_id + '\"class=\"card-link action\" data-toggle=\"collapse\" href=\"#collapse' + v.bal_mem_id+'\">'\r\n");
      out.write("\t\t\t\t\t\tcode += v.su_mem_id\r\n");
      out.write("\t\t\t\t\t\tcode += '</a>'\r\n");
      out.write("\t\t\t\t\t\tcode += '</div>'\r\n");
      out.write("\t\t\t\t\t\tcode += '<div id=\"collapse' + v.bal_mem_id +'\" class=\"collapse\" data-parent=\"#accordion\">'\r\n");
      out.write("\t\t\t\t\t\tcode += '<div class=\"card-body cbody\">'\r\n");
      out.write("\t\t\t\t\t\tcode += '<p class=\"p1 bodyp\">'\r\n");
      out.write("\t\t\t\t\t\tcode += '작성자 : <span class=\"wr\">' + v.mes_cont+ '</span> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'\r\n");
      out.write("\t\t\t\t\t\tcode += '이메일 : <span class=\"em\">' + v.mail + '</span> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'\r\n");
      out.write("\t\t\t\t\t\tcode += '조회수 : <span class=\"hit\">' + v.mes_num+ '</span> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'\r\n");
      out.write("\t\t\t\t\t\tcode += '날짜 : <span class=\"da\">' + v.date + '</span> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'\r\n");
      out.write("\t\t\t\t\t\tcode += '</p>'\r\n");
      out.write("\t\t\t\t\t\tcode += '<p class=\"p2\">'\r\n");
      out.write("\t\t\t\t//\t\tcode += '<input  data-toggle=\"modal\" data-target=\"#modifyModal\" type=\"button\" class=\"action\" name=\"modify\" idx=\"' + v.su_mem_id + '\" value=\"수정\">'\r\n");
      out.write("\t\t\t\t\t\tcode += '<input type=\"button\" class=\"action\" name=\"delete\" idx=\"' + v.su_mem_id + '\" value=\"삭제\">'\r\n");
      out.write("\t\t\t\t\t\tcode += '</p>'\r\n");
      out.write("\t\t\t\t\t\tcode += '<hr>'\r\n");
      out.write("\t\t\t\t\t\tcode += '<p class=\"p3 bcont\">'\r\n");
      out.write("\t\t\t\t\t\t//code +=  v.content.replace(/\\r/g, \"\").replace(/\\n/g, \"<br>\");\r\n");
      out.write("\t\t\t\t\t\tcode += '</p>'\r\n");
      out.write("\t\t\t\t\t\tcode += '<p class=\"p4\">'\r\n");
      out.write("\t\t\t\t\t\tcode += '<textarea cols=\"100\"></textarea>'\r\n");
      out.write("\t\t\t\t\t\tcode += '<input type=\"button\" class=\"action reply\" name=\"reply\" idx=\"'+ v.num +'\" value=\"등록\">'\r\n");
      out.write("\t\t\t\t\t\tcode += '</p>'\r\n");
      out.write("\t\t\t\t\t\tcode += '</div>'\r\n");
      out.write("\t\t\t\t\t\tcode += '</div>'\r\n");
      out.write("\t\t\t\t\t\tcode += '</div>' -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
