/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-02-18 00:30:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.work_005fysh;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.or.ddit.dcum.vo.ClassStudentVO;
import kr.or.ddit.dcum.vo.SubjectVO;
import kr.or.ddit.ysh.controller.subject;
import kr.or.ddit.dcum.vo.MemberVO;

public final class student_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.or.ddit.dcum.vo.SubjectVO");
    _jspx_imports_classes.add("kr.or.ddit.dcum.vo.MemberVO");
    _jspx_imports_classes.add("kr.or.ddit.ysh.controller.subject");
    _jspx_imports_classes.add("kr.or.ddit.dcum.vo.ClassStudentVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/student.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(" #sp{\r\n");
      out.write(" \tcolor: white;\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write(" #d6 {\r\n");
      out.write(" width : 600px;\r\n");
      out.write(" height :50px;\r\n");
      out.write("  \r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" .container{\r\n");
      out.write(" width: 880px;\r\n");
      out.write(" height: 50px;\r\n");
      out.write(" float: left;\r\n");
      out.write(" } \r\n");
      out.write(" \r\n");
      out.write(" .bbshCont{\r\n");
      out.write(" \t\r\n");
      out.write("\twidth: 1000px;\r\n");
      out.write("\theight: 1000px;\r\n");
      out.write(" \tfloat: left;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" #d1{\r\n");
      out.write("   height: 1000px;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" #tab1{\r\n");
      out.write(" width: 100%;\r\n");
      out.write(" height: 200px;\r\n");
      out.write(" \r\n");
      out.write(" }\r\n");
      out.write(" #tab2{\r\n");
      out.write("  width: 100%;\r\n");
      out.write(" height: 200px;\r\n");
      out.write(" }\r\n");
      out.write("  <!-- 새로만든 div -->\r\n");
      out.write("  #view2{\r\n");
      out.write("\tborder: 1px solid black;\r\n");
      out.write("\twidth: 600px;\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
 
MemberVO loginMember = (MemberVO)session.getAttribute("loginUser");


      out.write("\r\n");
      out.write("\r\n");
 

ClassStudentVO student = (ClassStudentVO)request.getAttribute("student");
SubjectVO subject = (SubjectVO)request.getAttribute("subject");

      out.write("\r\n");
      out.write("\r\n");
      out.write(" \t//성적 조회 \r\n");
      out.write(" \t//성적조회도 수정필요 점수값\r\n");
      out.write(" \t//요놈이 메인\r\n");
      out.write(" \t\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t$('#btn1').on('click',function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\tmemid = ");
      out.print( loginMember.getMem_id() );
      out.write(";\r\n");
      out.write("\t\t//2022-02-16 수정중\r\n");
      out.write("\t\t$.ajax({ \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/StudentSum.do\",\t\t\t\r\n");
      out.write("\t\t\tdata : {\"memid\" : memid},\r\n");
      out.write("\t\t\ttype :\"get\",\r\n");
      out.write("\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tcode = \"\";\r\n");
      out.write("\t\t\t\tcode+= '<table class=\"table table-striped\">';\r\n");
      out.write("\t\t\t\tcode+= '<tr>'\r\n");
      out.write("\t\t\t\tcode+= '<td><h3>'+ '");
      out.print(loginMember.getMem_name() );
      out.write("&nbsp&nbsp'+'님 의 영역별 취득 현황</h3>'+'</td>';\t\t\r\n");
      out.write("\t\t\t    code+= '</tr><tr>'\r\n");
      out.write("\t\t\t\tcode+=' <td><h4>'+ '");
      out.print(loginMember.getMem_name() );
      out.write("' + '님 확인후 문제시 담당자 연락부탁드립니다. ' + '</h4>'+'<td>';\r\n");
      out.write("\t\t\t\tcode+= '</tr>'\r\n");
      out.write("\t\t\t    code+= '</table>'\r\n");
      out.write("\t\t\t    code+= '<table class=\"table table-striped\" id=\"tab1\">';\r\n");
      out.write("\t\t\t    code+= '<tr>';\r\n");
      out.write("\t\t\t\tcode+= '<th>과목구분</th>';\r\n");
      out.write("\t\t\t\tcode+= '<th> </th>';\r\n");
      out.write("\t\t\t\tcode+= '<th>과목명</th>';\r\n");
      out.write("\t\t\t\tcode+= '<th> </th>';\r\n");
      out.write("\t\t\t\tcode+= '<th> </th>';\r\n");
      out.write("\t\t\t\tcode+= '<th></th>';\r\n");
      out.write("\t\t\t\tcode+= '<th>학과 점수</th>';\r\n");
      out.write("\t\t\t\tcode+= '</tr>';\r\n");
      out.write("\t\t\t\tcode+= '</thead>';\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar score = 0;\r\n");
      out.write("\t\t\t\t$.each(res, function(i, v ){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t    code+= '<tr>';\r\n");
      out.write("\t\t\t    code+= '<th>전공</th>';\r\n");
      out.write("\t\t\t    code+= '<td> </td>';\r\n");
      out.write("\t\t\t    code+= '<td>'+v.sub_name+'</td>';\r\n");
      out.write("\t\t\t    code+= '<td> </td>';\r\n");
      out.write("\t\t\t    code+= '<td> </td>';\r\n");
      out.write("\t\t\t    code+= '<td> </td>';\r\n");
      out.write("\t\t\t    code+= '<td>'+ v.sub_score +'</td>'; \r\n");
      out.write("\t\t\t    code+= '</tr>';\r\n");
      out.write("\t\t\t    score += Number(v.sub_score);\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tconsole.log(score)\r\n");
      out.write("\t\t\t    code+= '<tr>';\r\n");
      out.write("\t\t\t    code+= '<th>학과 취득 점수</th>';\r\n");
      out.write("\t\t\t    code+= '<td> </td>';\r\n");
      out.write("\t\t\t    code+= '<td> </td>';\r\n");
      out.write("\t\t\t    code+= '<td> </td>';\r\n");
      out.write("\t\t\t    code+= '<td> </td>';\r\n");
      out.write("\t\t\t    code+= '<td> </td>';\r\n");
      out.write("\t\t\t    code+= '<td>'+score+'</td>';  //(140-score)\r\n");
      out.write("\t\t\t    code+= '</tr>';\r\n");
      out.write("\t\t\t    code+= '</table>'; \r\n");
      out.write("\t\t\t    code+= '<br><br>';\r\n");
      out.write("\t\t\t    code+= '</div>';\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    $(\"#d1\").empty().append(code);\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    btn2();\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\talert(\"상태 : \" + xhr.status);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdataType : 'json'\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}) //클릭이벤트 종료\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t//$('#btn2').on('click',function(){\r\n");
      out.write("\t//성적조회 btn1 실행시 btn2 까지 자동실행\r\n");
      out.write("    btn2 = function() {\t\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl :  \"");
      out.print(request.getContextPath());
      out.write("/subject.do\",\r\n");
      out.write("\t\ttype : \"get\",\r\n");
      out.write("\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\trcode = \"\";\t\r\n");
      out.write("//         rcode+='<dd></dd>';\r\n");
      out.write("        rcode+='<div id=\"d5\">';\r\n");
      out.write("        rcode+='<span><h4>수강중인 과목</h4></span>';\r\n");
      out.write("        rcode+='<table class=\"table table-striped\"id=\"tab2\">';\r\n");
      out.write("        \r\n");
      out.write("       /*  rcode+='<colgroup>';\r\n");
      out.write("        rcode+='<col width=\"100px\"/>';\r\n");
      out.write("        rcode+='<col width=\"*\"/>';\r\n");
      out.write("        rcode+='<col width=\"100px\"/>';\r\n");
      out.write("        rcode+='<col width=\"100px\"/>';\r\n");
      out.write("        rcode+='<col width=\"100px\"/>';\r\n");
      out.write("        rcode+='</colgroup>';  */\r\n");
      out.write("        \r\n");
      out.write("        rcode+='<thead>';\r\n");
      out.write("        rcode+='<tr>';\r\n");
      out.write("        rcode+='<th>교과구분</th>';\r\n");
      out.write("        rcode+='<th>교과목명</th>';\r\n");
      out.write("        rcode+='<th>직급</th>';\r\n");
      out.write("        rcode+='<th>이름</th>';\r\n");
      out.write("        rcode+='<th> </th>';\r\n");
      out.write("        rcode+='</tr>';\r\n");
      out.write("        rcode+='</thead>';\r\n");
      out.write("        rcode+='<tbody><tr>';\r\n");
      out.write("        \r\n");
      out.write("        //2022-02-16 수정 본 교수 이름 , 직급 불러오기\r\n");
      out.write("        $.each(res, function(i, v ){\r\n");
      out.write("       \r\n");
      out.write("        rcode+='<th>전공</th>';\r\n");
      out.write("        rcode+='<td>'+ v.sub_name +'</td>';\r\n");
      out.write("        rcode+='<td>'+v.mem_sort_nm+'</td>';\r\n");
      out.write("        rcode+='<td>'+v.mem_name+'</td>';\r\n");
      out.write("        rcode+='<td> </td>'\r\n");
      out.write("        rcode+='</tr><tr>';\r\n");
      out.write("        \r\n");
      out.write("        })\r\n");
      out.write("      \r\n");
      out.write("        rcode+='</tr></tbody>';\r\n");
      out.write("        rcode+='</table></div>';\r\n");
      out.write("     \r\n");
      out.write("        $(\"#d1\").append(rcode);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\t\r\n");
      out.write("\t\terror : function(xhr){\r\n");
      out.write("\t\t\talert(\"상태 : \" + xhr.status);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t},\r\n");
      out.write("     \r\n");
      out.write("\t\tdataType : 'json'\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t} //2번째 펑션 종료\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//수강 관리  2022 - 02 - 15 부분수정 완료\r\n");
      out.write("\t $('#btn2').on('click',function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t memid =");
      out.print( loginMember.getMem_id() );
      out.write("\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t //수강신청 상태인 과목 가져오기 \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/SubjectList.do\",\r\n");
      out.write("\t\t\tdata : {\"memid\" : memid},\r\n");
      out.write("\t\t\ttype : 'get',\r\n");
      out.write("\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\ttcode='';\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\ttcode+='<div class=\"bbshCont\" >';\r\n");
      out.write("\t\t\t\ttcode+= '<h3>'+'");
      out.print(loginMember.getMem_name() );
      out.write("&nbsp&nbsp'+'님의 수강신청 페이지</h3>';\r\n");
      out.write("\t\t\t\ttcode+= '<br><br>'\r\n");
      out.write("\t\t        tcode+='<div class=\"bbsSub\"><h4>수강 신청</h4></div>';\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t        tcode+='<div class=\"fr\">'\r\n");
      out.write("\t\t        tcode+='</div>';\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t        tcode+='<div class=\"scrTable half page_11HR mt30\">'; \r\n");
      out.write("\t\t        tcode+='</div>';\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t        tcode+='<table  class=\"table table-striped\">';\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t        tcode+='<thead>';\r\n");
      out.write("\t\t        tcode+='<tr>';\r\n");
      out.write("\t\t        tcode+='<th>-</th>';\r\n");
      out.write("\t\t        tcode+='<th>과목코드</th>';\r\n");
      out.write("\t\t        tcode+='<th>교과목명</th>';\r\n");
      out.write("\t\t        tcode+='<th>학생정원</th>';\r\n");
      out.write("\t\t        tcode+='<th>교수명</th>';\r\n");
      out.write("\t\t        tcode+='<th>학점</th>';\r\n");
      out.write("\t\t        tcode+='<th>수강</th>';\t\t        \r\n");
      out.write("\t\t        tcode+='</tr>';\r\n");
      out.write("\t\t        tcode+='</thead>';\r\n");
      out.write("\t\t       \r\n");
      out.write("\t\t        tcode+='<tbody id=\"enrollView1\">';  \r\n");
      out.write("\t\t        $.each(res, function(i, v ){\r\n");
      out.write("\t\t         \r\n");
      out.write("\t\t\t        tcode+='<tr class=\"view\">';\r\n");
      out.write("\t\t\t        tcode+='<td>-</td>';\r\n");
      out.write("\t\t\t        tcode+='<td class=\"code\">'+v.sub_num+'</td>';\r\n");
      out.write("\t\t\t        tcode+='<td>'+v.sub_name+'</td>';\r\n");
      out.write("\t\t\t        tcode+='<td>'+v.sub_cnt+'</td>';\r\n");
      out.write("\t\t\t        tcode+='<td>'+v.mem_id+'</td>';\r\n");
      out.write("\t\t\t        tcode+='<td>'+v.status+'</td>';\r\n");
      out.write("\t\t\t        tcode+='<td><button type=\"button\" class=\"btn btn-primary bbsBtn\" >신청</button></td></tr>';\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t\t        //class=\"btn btn-outline-primary\r\n");
      out.write("\t\t        });\t\r\n");
      out.write("\t\t\t\ttcode+='</tbody>'\r\n");
      out.write("\t\t\t    tcode+='</table>'\t\t\r\n");
      out.write("\t\t\t    \r\n");
      out.write("// \t\t\t    tcode+='<br><br>'\r\n");
      out.write("\t\t       \r\n");
      out.write("\t\t\t    tcode +='<div id=\"view2\">'\r\n");
      out.write("\t\t\t    tcode +='<h4>수강신청 내역</h4>'\r\n");
      out.write("\t\t\t    tcode+='<table  class=\"table table-striped\">';\r\n");
      out.write("\t\t\t    tcode+='<thead>';\r\n");
      out.write("\t\t        tcode+='<tr>';\r\n");
      out.write("\t\t        tcode+='<th>No</th>';\r\n");
      out.write("\t\t        tcode+='<th>과목코드</th>';\r\n");
      out.write("\t\t        tcode+='<th>교과목명</th>';\r\n");
      out.write("\t\t        tcode+='<th>학생정원</th>';\r\n");
      out.write("\t\t        tcode+='<th>교수명</th>';\r\n");
      out.write("\t\t        tcode+='<th>학점</th>';\r\n");
      out.write("\t\t        tcode+='<th>수강</th>';\t\t        \r\n");
      out.write("\t\t        tcode+='</tr>';\r\n");
      out.write("\t\t        tcode+='<tbody id=\"enrollView2\">';\r\n");
      out.write("\t\t\t   tcode+='</table>'\r\n");
      out.write("\t\t\t   tcode +='</div>';\r\n");
      out.write("\t\t\t   \r\n");
      out.write("\t\t\t   tcode +='</div>';\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t   \r\n");
      out.write("\t\t\t   $('#d1').html(tcode);\r\n");
      out.write("\t\t\t   \r\n");
      out.write("\t\t\t   \r\n");
      out.write("\t\t\t   $.ajax({\r\n");
      out.write("\t\t\t\t    url : '");
      out.print(request.getContextPath());
      out.write("/SubjectList2.do',\r\n");
      out.write("\t\t\t    \tdata : {\"memid\" : memid},\r\n");
      out.write("\t\t\t    \ttype : 'get',\r\n");
      out.write("\t\t\t    \tsuccess : function(res){\r\n");
      out.write("\t\t\t    \t\t  \r\n");
      out.write("\t\t\t    \t\thcode=\"\";\r\n");
      out.write("\t\t\t    \t\t  \r\n");
      out.write("\t\t\t    \t\t$.each(res, function(i, v ){ \r\n");
      out.write("\t\t\t \t\t         \t\r\n");
      out.write("\t\t\t    \t\t\t \r\n");
      out.write("\t\t\t    \t\t\t  \r\n");
      out.write("\t\t\t\t\t\t    hcode+='<tr class=\"view3\">';\r\n");
      out.write("\t\t\t\t\t\t    hcode+='<td>-</td>';\r\n");
      out.write("\t\t\t\t\t\t    hcode+='<td class=\"code2\">'+v.sub_num+'</td>';\r\n");
      out.write("\t\t\t\t\t\t    hcode+='<td>'+v.sub_name+'</td>';\r\n");
      out.write("\t\t\t\t\t\t    hcode+='<td>'+v.sub_cnt+'</td>';\r\n");
      out.write("\t\t\t\t\t\t    hcode+='<td>'+v.mem_id+'</td>';\r\n");
      out.write("\t\t\t\t\t\t    hcode+='<td>'+v.status+'</td>';\r\n");
      out.write("\t\t\t\t\t\t    hcode+='<td><button type=\"button\" class=\"btn btn-danger cancel\" data=\"'+v.sub_num+'\" >신청취소</button></td></tr>';\r\n");
      out.write("\t\t\t    \t\t  \r\n");
      out.write("\t\t\t    \t\t});\r\n");
      out.write("\t\t\t    \t\t\r\n");
      out.write("\t\t\t    \t      $('#enrollView2').html(hcode);\r\n");
      out.write("\t\t\t    \t      \r\n");
      out.write("\t\t\t    \t      \r\n");
      out.write("\t\t\t    \t\r\n");
      out.write("\t\t\t    \t},\r\n");
      out.write("\t\t\t    \tdataType : 'json'\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t   })//ajax 종료\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\talert(\"상태 : \" + xhr.status);\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdataType : 'json'\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\r\n");
      out.write("\t   }) // 이벤트 종료\r\n");
      out.write("\t   //삭제버튼 활성화\r\n");
      out.write("\t   \r\n");
      out.write("\t   $('#d1').on('click','.cancel',function(){\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t   yn = confirm(\"정말 삭제 하시겠습니까?\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t   if(yn){\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t$(this).parents('.view3').remove();\r\n");
      out.write("\t\t   }\t\t\r\n");
      out.write("\t\t   \r\n");
      out.write("\t   \tsubnum = $(this).parents('.view3').find(\".code2\").text();\r\n");
      out.write("\t   \r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : '");
      out.print(request.getContextPath());
      out.write("/DeleteSubject.do',\r\n");
      out.write("\t\t\tdata : {\"subnum\" : subnum},\r\n");
      out.write("\t\t\ttype : 'get',\r\n");
      out.write("\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\talert(\"상태 확인 :\" + xhr.status);\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdataType : 'json'\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t})//ajax 종료\r\n");
      out.write("\t\t\r\n");
      out.write("\t   \r\n");
      out.write("\t   \r\n");
      out.write("\t   \r\n");
      out.write("\t   })//onclick 이벤트 종료\r\n");
      out.write("\t   \r\n");
      out.write("\t   \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\t//수강신청 append , parents , 수정완료 취소버튼활성화\r\n");
      out.write("\t \t$('#d1').on('click','.bbsBtn', function(){\r\n");
      out.write("\t \r\n");
      out.write("\t \t\t confirm(\"수강 신청 하시겠습니까?\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t // 2022 - 02 - 16 수정본 \t\r\n");
      out.write("\t\tsubnum = $(this).parents('.view').find(\".code\").text();\r\n");
      out.write("\t\tuserid = ");
      out.print( loginMember.getMem_id() );
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar selTr = $(this).parents(\".view\").html();  //tr없다 \r\n");
      out.write("\t\t\tconsole.log(selTr);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* $(this).text(\"신청취소\");\r\n");
      out.write("\t\t\t$(this).attr(\"class\", \"cancel\"); */\r\n");
      out.write("\t\t\t$(this).parents(\".view\").remove();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t//$(\"#enrollView2\").append(selTr.html());\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t//selTr.remove();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/viewInsert.do\",\r\n");
      out.write("\t\t\t\tdata:{\r\n");
      out.write("\t\t\t\t\t\"subnum\" : subnum,\r\n");
      out.write("\t\t\t\t\t\"userid\" : userid\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tt = \"<tr class='view3'>\";\r\n");
      out.write("\t\t\t\t\tt += selTr;\r\n");
      out.write("\t\t\t\t\tt += \"</tr>\"\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$('#enrollView2').append(t);\r\n");
      out.write("\t\t\t\t\t$('#enrollView2 .view3 .bbsBtn').text(\"신청취소\");\r\n");
      out.write("\t\t\t\t\t$('#enrollView2 .view3 .bbsBtn').attr(\"class\",\"btn btn-danger cancel\");\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\t\talert(\"상태 : \" + xhr.status);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType : \"json\"\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t \t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t//학적을 조회하는 ajax\r\n");
      out.write("\t\t$('#btn3').on('click',function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tmemid = ");
      out.print(loginMember.getMem_id() );
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write(" \t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/StudentList.do\", \r\n");
      out.write("\t\t\t\tdata : {\"memid\" : memid },\r\n");
      out.write(" \t\t\t\ttype: \"get\",\r\n");
      out.write(" \t\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write(" \t\t\t\tIcode = \"\";\t\r\n");
      out.write(" \t\t\t\tIcode +='<div>'\r\n");
      out.write(" \t\t\t\tIcode +='<h2>학생 정보</h2>'\r\n");
      out.write(" \t\t\t\tIcode +='<p><h4>환영합니다. DDIT UNIVERSITY</h4></p>'\r\n");
      out.write(" \t\t\t\tIcode +='<div class=\"card\" style=\"width:400px\">'\r\n");
      out.write(" \t\t\t\tIcode +='<img class=\"card-img-top\" src=\"../images/main/사자2.jpg\" alt=\"Card image\" style=\"width:100%\">'\t\r\n");
      out.write(" \t\t\t\tIcode +='</div>'\r\n");
      out.write(" \t\t\t\tIcode +='</div>'\r\n");
      out.write(" \t\t\t\tIcode +='<br>'\r\n");
      out.write(" \t\t\t\tIcode += '<table class=\"table table-striped\">'\r\n");
      out.write(" \t\t\t\tIcode += '<thead>'\r\n");
      out.write(" \t\t\t\tIcode += '<tr>'\r\n");
      out.write("\t\t\t\tIcode += '<th><h2>'+'");
      out.print(loginMember.getMem_name());
      out.write("&nbsp&nbsp'+'님의 학적 정보</h2></th>' \r\n");
      out.write(" \t\t\t\tIcode += '</tr><tr>'\r\n");
      out.write(" \t\t\t\tIcode += '<th><p><h4>학적 변동시 관리자에게 문의해주세요.</h4></p></th>'            \r\n");
      out.write(" \t\t\t\tIcode += '</tr></thead>'\r\n");
      out.write(" \t\t\t\tIcode += '<table class=\"table table-striped\">'\r\n");
      out.write(" \t\t\t\tIcode += '<thead>'\r\n");
      out.write(" \t\t\t\tIcode += '<tr>'\r\n");
      out.write(" \t\t\t\tIcode += '<th>나의 학번</th>'\r\n");
      out.write(" \t\t\t\tIcode += '<th>나의 학과</th>'\r\n");
      out.write(" \t\t\t\tIcode += '<th>입 학 일</th>'\r\n");
      out.write(" \t\t\t\tIcode += '<th>졸업여부</th>'\r\n");
      out.write(" \t\t\t\tIcode += '</tr>'\r\n");
      out.write(" \t\t\t\tIcode += '</thead>'\r\n");
      out.write(" \t\t\t\t\r\n");
      out.write(" \t\t\t\t$.each(res,function(i, v){\r\n");
      out.write(" \t\t\t\tIcode += '<tbody>'\r\n");
      out.write(" \t\t\t\tIcode += '<tr>'\r\n");
      out.write(" \t\t\t\tIcode += '<td>'+v.mem_id+'</td>'\r\n");
      out.write(" \t\t\t\tIcode += '<td>'+v.dep_num+'</td>'\r\n");
      out.write(" \t\t\t\tIcode += '<td>'+v.start_date+'</td>'\r\n");
      out.write(" \t\t\t\tIcode += '<td>'+v.end_date+'</td>'\t\t\t\t\r\n");
      out.write(" \t\t\t\tIcode += '</tr>'\r\n");
      out.write(" \t\t\t\tIcode += '</tbody>'\t\t\r\n");
      out.write(" \t\t\t\t})\r\n");
      out.write(" \t\t\t\tIcode += '</table>'\r\n");
      out.write(" \t\t\t\tIcode += '<br><br>'\r\n");
      out.write(" \t\t\t\tIcode += '<p><h4>학적 변동시 관리자에게 문의해주세요.</h4></p>' \r\n");
      out.write(" \t\t\t\tIcode += '<table class=\"table table-striped\">'\r\n");
      out.write(" \t\t\t\tIcode += '<thead>'\r\n");
      out.write(" \t\t\t\tIcode += '<tr>'\r\n");
      out.write(" \t\t\t\tIcode += '<th>재학 여부</th>'\r\n");
      out.write(" \t\t\t\tIcode += '<th>총 점수</th>'\r\n");
      out.write(" \t\t\t\tIcode += '</tr>'\r\n");
      out.write(" \t\t\t\tIcode += '</thead>'\t\t\t\r\n");
      out.write(" \t\t\t\t$.each(res,function(i, v){\r\n");
      out.write(" \t\t\t\tIcode += '<tbody>'\r\n");
      out.write(" \t\t\t\tIcode += '<tr>'\r\n");
      out.write(" \t\t\t\tIcode += '<td>'+v.status+'</td>'\r\n");
      out.write(" \t\t\t\tIcode += '<td>'+v.total_score+'</td>'\t\t\t\r\n");
      out.write(" \t\t\t\tIcode += '</tr>'\r\n");
      out.write(" \t\t\t\tIcode += '</tbody>'\t\t\r\n");
      out.write(" \t\t\t\t})\r\n");
      out.write(" \t\t\t\t\r\n");
      out.write(" \t\t\t\tIcode += '</div>'\r\n");
      out.write(" \t\t\t\t\t$(\"#d1\").empty().append(Icode);\r\n");
      out.write(" \t\t\t\t},\r\n");
      out.write(" \t\t\t\terror : function(xhr){\r\n");
      out.write(" \t\t\t\t\talert(\"상태 : \" + status); \r\n");
      out.write(" \t\t\t\t},\r\n");
      out.write(" \t\t\t\tdataType : 'json'\r\n");
      out.write(" \t\t\t})\r\n");
      out.write(" \t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-sm bg-dark navbar-dark\">\r\n");
      out.write("  <!-- Brand/logo -->\r\n");
      out.write("  <a class=\"navbar-brand\" href=\"#\">\r\n");
      out.write("    <img src=\"../images/icon/학사관리.png\" alt=\"gdff\" style=\"width:40px;\">\r\n");
      out.write("  </a>\r\n");
      out.write("  \r\n");
      out.write("  <!-- Links -->\r\n");
      out.write("  <ul class=\"navbar-nav\">\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"#\" id=\"btn1\">성적관리</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"#\" id=\"btn2\">수강관리</a>\r\n");
      out.write("    </li>\r\n");
      out.write("     <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"#\" id=\"btn3\">학적관리</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/allProfessorList.do\" id=\"btn4\">휴학/복학/자퇴관리</a>\r\n");
      out.write("    </li>\r\n");
      out.write("\r\n");
      out.write("  </ul>\r\n");
      out.write("   <span id=\"sp\"><h4>[");
      out.print(loginMember.getMem_sort_nm());
      out.write(']');
      out.write(' ');
      out.print(loginMember.getMem_name() );
      out.write("님 반갑습니다.</h4></span>\r\n");
      out.write("</nav>\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"d1\">\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
